open-telemetry/opentelemetry-demo

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/workflows/checks.yml
- .github/workflows/stale.yml
- .markdownlint.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- LICENSE
- docfx.json
Added the following stuff (most of them were stolen from spec and sdk repo):
* CODEOWNERS
* CHANGELOG.md
* issue templates
* PR template
* license
* basic CI workflow
> Adding the basic stuff

- README.md
Added maintainer/approvers & scheduling information.
> added contributors information to readme

- Requirements/Application-Requirements.md
- Requirements/OpenTelemetry-Requirements.md
- Requirements/README.md
- Requirements/System-Requirements.md
Translated the requirements into markdown files. Planning on linking to these from the overall readme after the initial drafts are approved.
Requirements doc can be found here: https://docs.google.com/document/d/1ncCKFzgUf8XX7dw6a0U31RNYnPHhHg1s5cF-qYLlmEU/edit#
> Added application, system, & otel requirement pages

- CHANGELOG.md
- pb/demo.proto
Protos for issue #28 
This adds the feature flag service protos. I figured this was the best place to start with adding this service. 
I can open a design discussion issue like the check boxes below say but I thought this might be simply enough to just open a PR. I didn't include anything beyond a feature flag having a name and a bool, to keep it simple. I assume we don't want stuff like variants/experiments/etc, but could easily add them to this PR if they are.
---
> add feature flag service to proto file

- README.md
- docs/v1Graph.md
Contributes to #30 -
- Update service graph diagram with new + modified services
- Add legend
> Add desired service map

- src/checkoutservice/main.go
- src/productcatalogservice/server.go
- src/shippingservice/main.go
A sampling strategy hasn't been defined for our application yet. Several Go apps use explicit sampling but no where else. Removing the always on sampler until we have a strategy.
> remove explicit sampling until sampling strategy is defined

- src/emailservice/Dockerfile
If I had invested, say, a mere modicum of effort into understanding what
needed to be done to use a `-slim` image in the first place, then we
would have included this in #109 from the start. However, I clearly did not. :facepalm:
This change switches us to the `-slim` image, and installs the one thing
we actually need to build `puma`: Debian's `build-essential` package.
> ruby: switch to `-slim` image

- README.md
- Requirements/architecture-requirements.md
Converted the architecture google doc into a markdown file. https://docs.google.com/document/d/1toQqAa4GApjFN3bvkEsq98Rb7WtbeKr3whsipAB3j1Q/edit
Tentatively placed it in the requirements folder but docs may be a better place.
> Added architecture information to repo. 

- README.md
- pb/README.md
File not necessary and currently gets copied unnecessarily in the `Dockerfile`s - that could be avoided by making the copy commands only copy all `*.pb` but I'm not sure how much explaining is needed for this file that can't be done in the self-contained comments. Each service should explain in their own `README.md` files what types of requests they can receive and what their responses will look like and any outgoing requests too?
- Replaces https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/131 (see [discussion started to avoid these kind of PR open and closes](https://discord.com/channels/@me/287436405045460993/986372501145808956))
> Remove `/pb/READMD.md` file

- src/frontend/README.md
Updated standard feature tables to have more metric information with links
> add metric links to frontend readme

- src/emailservice/Dockerfile
Fixing an emailservice build problem.
The build is currently failing when running
`docker-compose up`
Problem:
`Step 3/8 : COPY Gemfile* .
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR: Service 'emailservice' failed to build : Build failed`
Dockerfile updated to fix the build.
> Fixing an emailservice build problem.

- README.md
Add some descriptions for metric feature.
> add some descriptions for metric feature

- docs/manual_span_attributes.md
With all the services being instrumented manually, it would be great if we could keep the span attributes documented.
I've went through all services and the opened PRs to create the initial  file.
From this, we can keep it updated whenever new PRs arrive, and we can follow a naming convention across all services.
> Add list of all manual attributes

- src/cartservice/src/cartservice.csproj
- src/cartservice/src/services/CartService.cs
Towards #51.
* New attributes and events attached to existing spans.
* Bump versions of instrumentation packages.
> [cartservice] Add manual instrumentation

- src/featureflagservice/config/runtime.exs
Fixes FeatureFlag Service not booting in environments where ipv6 is not available.
The IP the HTTP service listens on is changed from an ipv6 to ipv4 address.
> featureflagservice: use ipv4 address for http endpoint

- docker-compose.yml
Mostly to cut down on the size of the name that appears in the logs.
Before
After
One thing to note is that if you run more than 1 of an image at the [same time this name will be ignored](https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name)
> Add container_name s to compose file

- src/paymentservice/Dockerfile
Fixes #213 .
- (payment service) Add commands to install dependencies (python, make, g++) for arm64.
> Add commands to install dependencies for arm64

- README.md
I'm nominating Ziqi, @fatsheep9146, to join the approvers team. He's been making consistent contributions to the demo for several months, has been completing PR reviews, added our major metric pieces, & is active over Slack / github repo issues.  
A link to his previous PRs: https://github.com/open-telemetry/opentelemetry-demo-webstore/pulls?q=is%3Apr+author%3Afatsheep9146+is%3Aclosed
> add ziqi zhao as an approver

- src/paymentservice/package-lock.json
- src/paymentservice/package.json
No issue was opened, but I brought this up in slack: https://cloud-native.slack.com/archives/C03B4CWV4DA/p1657607127541249
When running the demo in WSL the `paymentservice` didn't have spans in Jaeger.
- Updated the OTel packages version
- Added the following missing dependencies:
- `"@grpc/proto-loader"`
- `"@opentelemetry/api"`
> [paymentservice] Add missing dependencies

- src/paymentservice/charge.js
Switch from `transaction_id` to `transactionId`
Fixes the payment service e2e test and also the 
Replace the change in this closed PR https://github.com/open-telemetry/opentelemetry-demo/pull/197 with simpler, more targeted fix.
Passing test screenshot
> [paymentservice] Fix transactionId in JSON response

- docker-compose.yml
This change will limit the amount of logs accrueing in docker
to 2 segments à 5M and prevents the demo from flooding the disk
which is useful in long-running demos.
> Limit size of accumulating logs sensibly

- docker-compose.yml
- src/emailservice/email_server.rb
This is a follow-up to #248, which in turn was resolving: https://github.com/open-telemetry/opentelemetry-demo/pull/242#discussion_r933603430
The ruby app is relying on convention, and by convention a `PORT` env
varable will determine which port the `puma` webserver actually listens
on. So - we don't need to set it explicitly in the compose file, but
that means we need to set it elsewhere somehow.
I tried a few hacks with the dockerfile:
- Trying to pass `PORT=$EMAIL_SERVICE_PORT`
- Trying to pass `-p $EMAIL_SERVICE_PORT` in the command
But those didn't work and I gave up. So instead we just set it directly
in the sinatra app ourselves. (Please don't ask me how that actually
gets set down all the way through sinatra -> rack -> puma, because
truthfully I do not know: rack-based servers are …
> emailservice: remove explicit `PORT` env variable

- CHANGELOG.md
- README.md
Pointing to our helm chart in our docs
> add helm chart to main readme

- CHANGELOG.md
- docs/manual_span_attributes.md
- src/currencyservice/src/server.cpp
Adds span attributes to currency conversion request
> [currency] - add span attributes

- Makefile
When working with the Erlang/Elixir feature flag service, the developer may encounter an error on some make commands. 
This PR Excludes the `_build` and `deps` build artifact folders from `ALL_DOCS` in Makefile. Allows developers to run `make markdownlint` without getting errors on 3rd party readme files downloaded from the Elixir toolchain.
> [featureflag] - exclude erlang/elixir build artifacts in makefile

- src/currencyservice/Dockerfile
Fixes #.
`currencyservice` is running under shell with pid>1 inside container. Which makes it difficult to send signals using `docker kill` command. Changed to run it as pid=1 so it can get catch the TERM/INT signal through `docker kill` command.
> Fix processid(pid) for currencyservice

- README.md
The UI is for a user to create/edit/toggle flags, services like the CheckoutService talk to the feature flag (grpc) server.
> fix diagram: services speak to featureflag server not its ui

- docker-compose.yml
This should fix the issue where the FeatureFlagService migrations fail because postgres isn't actually "ready" it is only "started". 
Instead of depending only on the postgres container being started it now depends on it being healthy too.
A problem is that `condition: service_healthy` is not in the compose v3 docs (only v2). But it does seem that it might be working.
If it doesn't work in v3 I'd argue we should switch to v2. Unless there are features from v3 being used (I don't see any) then use of v2 (specifically `version: '2.4'`) makes sense. My understanding is that v3 isn't really an update to compose v2 but that they can be thought of as separate, where v3 is meant for Swarm use.
> featureflagservice: add healthcheck to postgres dependency

- .env
Fixes- Docker image tag issue. We have updated 0.1.0 image when we released 0.3.0 .
We need to further investigate why/how 0.2.0-alpha release didn't have same issue.
> Update Image version to fix docker image tag

- docs/manual_span_attributes.md
- src/productcatalogservice/main.go
- Updates attribute names to be normalized with other services
ref: https://docs.google.com/spreadsheets/d/1cGmYKfl9GAzCnQaG5iP-RoSZ-0R_Nm8hutg-EFotmsE/edit#gid=0
> [productcatalog] span attributes update

- src/emailservice/email_server.rb
This PR is meant to help clean up the log output when doing a `docker compose up`. The email service adds an entry for the entire contents of the order confirmation email, creating unnecessary noise in the logs.
- removes email body from log output
> [email] remove email body from log

- CHANGELOG.md
- src/shippingservice/src/shipping_service.rs
It seems that #54 was closed without having all items checked.
Adding events to the spans `get-quote` and `ship-order`.
> [shippingservice] - Add events

- README.md
Clearly not an urgent PR, but I happened to notice that it didn't
mention that we have an HTTP service. I updated the docs to mention
that, and annotated the (quite nice) mermaid graph with the `HTTP`
annotation as well.
> Update README to mention that the emailservice is HTTP

- README.md
Add New Relic's fork of the demo to the list of vendor demos.
> Add New Relic to list of demos

- .env
- CHANGELOG.md
- docker-compose.yml
- docs/docker_deployment.md
References #252 and Fixes #349
This change makes it so people can go from git clone to seeing telemetry in under 2 minutes.
Makes use of docker image cache when running the application. This does not reduce build times. This change uses cache to reference existing images allowing users to run `docker compose up --no-build` and get a running demo application in about 90 seconds.
Building from main is still an initial 20 min ordeal for those that want to use the very latest.
> Reduce initial run time

- README.md
Complements #370.
Added PHP to mermaid chart.
> Add php mermaid

- src/quoteservice/Dockerfile
pecl is installing an older version of protobuf by default, that does not work in php8.1. Force it to 3.21.5
> bumping protobuf extension

- .github/workflows/checks.yml
docfx is failing on relative links to folders. We require these types of links for our service docs.
Per the SIG meeting on 9/26, we determined that the docfx checks were providing no value-add and should be removed.  This PR comments out the check (we can remove it completely on a subsequent PR)
> remove docfx check

- docs/services/paymentservice.md
Adds documentation for payment service, focused on instrumentation code.
This service makes use of Baggage which should get its own section. I added it after Metrics and Logs which are currently marked TBD.  not sure if we go with this or a different approach.
> [payment] document instrumentation

- docs/services/emailservice.md
Adds documentation for email service, focused on instrumentation code.
> [email] document instrumentation

- src/cartservice/src/Startup.cs
- src/cartservice/src/cartservice.csproj
Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/177
Adds .NETs runtime instrumentation metric to the cart service. Dashboards will follow in future PR. Also will add more instrumentations (http) in next PR.
Example metric:
> Add runtime metrics to cartservice

- docs/metric_service_features.md
- src/cartservice/src/Startup.cs
- src/cartservice/src/cartservice.csproj
- src/cartservice/src/cartstore/RedisCartStore.cs
Also updated version from 1.3.0 to 1.3.1 as 1.3.0 was deprecated due to vulnerability.
See metrics:
> [Cart] Added instrumentation for Asp.Net Core (http server)

- src/featureflagservice/rel/overlays/bin/server
Fixes #398 .
Changes the startup shell script for the feature flag service to exit with a failure code if the migration command fails. This causes the pod to be automatically restarted in Kubernetes. In my tests, it always restarts once before successfully connecting to the database.
> Exit featureflagservice startup script if migrations fail

- CHANGELOG.md
- src/checkoutservice/Dockerfile
- src/checkoutservice/go.mod
Copying over Julianos changes while he's blocked
> update go version

- src/recommendationservice/recommendation_server.py
- There was a fault in the recommendation logic that it offered also the same products which the user just opened (product page) or added to the cart (shopping cart page). The filtering logic not to recommend the same products was fixed.
- Minor refactoring.
> Fix recommendation logic not to recommend the selected product

- docker-compose.yml
Sets max traces in memory to the most recent 10000. This gives about 40-45 minutes of usage data before being maxed out. Memory consumption for this load is approximately 211 MiB
> [jaeger] limit memory usage

- src/loadgenerator/locustfile.py
Removes the `sessionId` populated as a UUID from `get_recommendations`. Since this request is a GET, and Locust keeps stats on each unique URL, adding a UUID to each one was bloating the internal stats from Locust.
> [loadgenerator] fix memory leak

- CHANGELOG.md
- docker-compose.yml
- src/otelcollector/otelcol-config.yml
Fixes #424.
Jaeger has officially switched to recommend OTLP as the ingestion protocol. OpenTelemetry spec might consider aligning this effort https://github.com/open-telemetry/opentelemetry-specification/pull/2858.
This PR replaces the Jaeger exporter to the OTLP exporter.
> [collector] replace Jaeger to OTLP exporter

- docker-compose.yml
- src/frontend/Dockerfile
- src/frontend/README.md
Fixes #407 .
When moving from `CMD` to `ENTRYPOINT` we forgot to update the instructions for the frontend local development.
Also, the `quoteservice`was added as a dependency of `frontend` to avoid errors during local development.
> [frontend] fix local development instructions and dependencies

- .github/workflows/checks.yml
This finishes removing the docfx check we had. It was commented out in #385 
A bonus side effect will be removing this GitHub beta warning in our PR code views.
> finish removing docfx check

- src/frontend/providers/Currency.provider.tsx
Sorts the list of currencies in the currency selector.
> [frontend] - sort currency list

- CHANGELOG.md
- docker-compose.yml
Sets reasonable memory limits for all services, based on an 80% memory target for each service, running the app for 7 days (minimum of 20M).
Data used by this PR incorporated the memory limits shown in the chart above which is a 7-day run on EKS. Some exceptions for loadgenerator, email, and quote services where I used data from docker stats after running the app on my local machine for several days.
- loadgenerator - the above didn't incorporate the memory leak fix
- email - I guess we have another small bug in the Helm chart since the email service wasn't listening on the proper port and I didn't notice :(, instead I used data from docker stats. I think we also have an issue with this service since it continues to eat memory erratically after running for several hours.
- quote - I'm not …
> set memory limits for all services

- src/currencyservice/src/server.cpp
Removes baggage processing from the currency service. Previously it would take all items from baggage and emit them as a span, which is not the desired behavior.
> [currency] - remove baggage processing

- docs/feature_flags.md
- src/featureflagservice/priv/repo/migrations/20220524172636_create_featureflags.exs
Removal of shippingFailure feature flag, which is not implemented (doesn’t do anything).
> Remove unimplemented feature flag: shippingFailure

- .github/workflows/release.yml
- CHANGELOG.md
Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/458
> Images support multi arch

- .github/workflows/release.yml
Reverts release automation due to permissions issues with branch protection on main.
> Revert envfile updates

- docker-compose.yml
Re-organize the order of service definitions in docker-compose.yml.  No functional changes were made. The change is made to make it easier to find service definitions in the large file. Order of service definitions is now:
Core demo services sorted alpha
Ancillary services sorted alpha
Tests sorted alpha
> organize order of service definitions in docker-compose.yml

- .github/component_owners.yml
- .github/workflows/assign-reviewers.yml
This would allow @jack-berg @mateuszrzeszutek and me to get pinged on any PRs that touch the Java app so we can help review. @dyladan's component-owners github action is being used in a few other otel repos already: https://github.com/search?q=org%3Aopen-telemetry+dyladan%2Fcomponent-owners&type=code
> Add component owners for adservice Java app

- src/frontend/components/CartItems/CartItems.tsx
- src/frontend/gateways/Api.gateway.ts
- src/frontend/pages/api/shipping.ts
- src/frontend/services/ProductCatalog.service.ts
Referencing oscars PR. I'll add a link later
> fix currency bug

- src/otelcollector/otelcol-config.yml
`metrics/spanmetrics` pipeline is not being used. Removing it along with unused `otlp/spanmetrics` receiver.
> Remove redundant components from collector config

- README.md
- Add Helios to the main README, to the list of demos featuring Online Boutique
> Add Helios to the list of demos featuring Online Boutique

- src/emailservice/views/confirmation.erb
The template used for the confirmation email in the emailservice did not render the nanos of the shipping cost. This commit adds them, so the rendering of shipping cost and item cost (lower in the template) is equivalent.
This is a minor fix.
> Render shipping cost nanos in emailservice

- CHANGELOG.md
- src/quoteservice/Dockerfile
- src/quoteservice/public/.htaccess
PHP-CLI is a PHP built-in server and should not be used in production, more info here: https://www.php.net/manual/en/features.commandline.webserver.php#features.commandline.webserver.
In order to have a service that users can relate to real life services, I've updated the QuoteService to make use of PHP-Apache.
I've also added OPcache in order to improve the PHP performance: https://www.php.net/manual/en/intro.opcache.php
> [quoteservice] Replace php-cli to php-apache

- CHANGELOG.md
- src/currencyservice/Dockerfile
Create multiple build jobs to run the currency service build in parallel and optimize build time. 
Different commands are needed to find the number of available CPU cores per OS.
`make -j$(nproc || sysctl -n hw.ncpu || echo 1)`
- Uses `nproc` on Linux
- Uses `sysctl -n hw.ncpu` on macOS
- Uses 1 core for others
Currency service had the longest build time among the Demo App services.
Rough build time improvements with this change:
- Linux, docker (Ryzen 5 5600G): 1000 s -> 400 s.
- macOS, docker desktop (M1 Pro): 750 s -> 450 s.
Measured with:
`docker compose build currencyservice --no-cache`
> [currencyservice] Create multiple build jobs to optimize build time

- docker-compose.yml
fix #556. 200M seems a reasonable upgrade. 
I could see us landing somewhere ~180M if we wanted to be extra mindful of memory allocation but it would require more testing.
> fix feature flag memory restarts

- README.md
Adding aspecto to the list of vendors.
We forked the repo and added instructions on how to configure it to send traces to aspecto
Thank you :)
> Add aspecto fork to demos list

- src/grafana/provisioning/datasources/jaeger.yaml
Fixed the datasource URL for the Jaeger within Grafana conf.
Thanks @jpkrohling for pointing that out!
> Fix grafana datasource Jaeger URL

- README.md
Fixes https://github.com/open-telemetry/opentelemetry-demo/pull/591#discussion_r1026745185
changed Appdynamics to AppDynamics (correct name) in vendor list.
> fixed typo in AppDynamics name

- docs/services/shippingservice.md
- src/shippingservice/Cargo.lock
- src/shippingservice/Cargo.toml
- src/shippingservice/src/shipping_service.rs
Fixes #596 
* use OTEL semantic conventions where defined
* name tracer in accordance with other services which sink grpc transactions
* name span in accordance with OTEL grpc conventions
* set SpanKind to SERVER for functions sinking grpc transactions
* set RpcSystem to grpc
* Set RpcGrpcStatusCode appropriately
> [shippingservice] add grpc conventions

- src/frontend/utils/telemetry/InstrumentationMiddleware.ts
Runs `InstrumentationMiddleware.ts` through prettier formatting. See: https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontend/.prettierrc.
Main change here is that tab width -> `2`
> [frontend] Format InstrumentationMiddleware.ts with prettier

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Add documentation requirements to various contrib assets

- CHANGELOG.md
- src/frontend/components/Ad/Ad.tsx
- src/frontend/gateways/Api.gateway.ts
- src/frontend/gateways/rpc/Ad.gateway.ts
- src/frontend/pages/api/data.ts
- src/frontend/pages/cart/checkout/[orderId]/index.tsx
- src/frontend/pages/cart/index.tsx
- src/frontend/pages/product/[productId]/index.tsx
- src/frontend/providers/Ad.provider.tsx
- src/frontend/tsconfig.json
- src/loadgenerator/locustfile.py
Fixes #586.
1. Pass `categories` as an input for Ad service
2. Randomize the ad shown, in case there are multiple ads in a response.
3. I had to bump the TS target to ES2015 to be able to use `Set`. I hope this is OK for a demo.
> Fix #586: Pass `categories` as an input for Ad service

- README.md
This adds a link to the Splunk fork of the OpenTelemetry demo repository.
> Add Splunk

- CHANGELOG.md
- docs/services/shippingservice.md
- src/shippingservice/Cargo.lock
- src/shippingservice/Cargo.toml
- src/shippingservice/src/main.rs
- src/shippingservice/src/shipping_service/quote.rs
I propose to add a dedicated http client span for the outgoing calls to `/getquote`. This change will provide tracing separation between the server part and the downstream requests client part inside shippingservice. A client span can also better match with the peer quoteservice server span. The client middleware-based instrumentation uses the available `reqwests-tracing` and `tracing-opentelementry` crates.
> shippingservice: add http client request span

- .gitignore
Adds `.dockerhub.env` and `.ghcr.env` to gitignore
These are meant to be used as part of the release process or local dev.
> [chore] add build-and-push env files

- src/shippingservice/Cargo.toml
In 1.2, the new tracing crates for reqwest used the default subscriber, which picks up everything from `trace` level on up. Thanks to the tireless efforts of the rust community, this means we get spans and span events for quite literally everything! While great for detailed inspection of performance, not so great for our purposes. This PR reduces the verbosity at build time to something reasonable (`info`), giving us our http client spans without murdering our poor jaeger instances.
> Reduce rust trace verbosity.

- docs/current_architecture.md
Uses `TypeScript` as the language type for the frontend service in the architecture diagram. Though this compiles to JavaScript, the OpenTelemetry docs do split this out, and it's good to call this out as an example in the demo as well.
this also reorders the languages graph in alpha order
> [chore] - show TypeScript for frontend in arch diagrams

- ide-gen-proto.sh
Previously `make generate-protobuf` only copied the demo.proto file but did not generate the protobuf classes required for IDEs to resolve imports. This adds the command to generate the protobuf classes.
> [chore] fix generate protobuf for TypeScript

- README.md
Add TelemetryHub to the vendor list.
This is just a README change; I do not believe the following are necessary:
> Add TelemetryHub to vendor list

- src/frontend/pages/cart/checkout/[orderId]/index.tsx
- src/frontend/types/Cart.ts
This change benefits IDEs so they can properly detect and find type declarations. It adds `shippingAddress` to the `IProductType` type so that code in the cart checkout order page can properly detect the declaration.
> [frontend] add address to IProductCheckout type

- CHANGELOG.md
- docker-compose.yml
- docs/services/quoteservice.md
- src/quoteservice/Dockerfile
- src/quoteservice/README.md
- src/quoteservice/app/routes.php
- src/quoteservice/composer.json
- src/quoteservice/public/index.php
- update to opentelemetry-php beta versions
- import only required opentelemetry-php libraries
- use php auto-instrumentation (remove most manual instrumentation, leaving enough to illustrate that auto+manual can work together)
- bump php to 8.2, the most recent version supported by opentelemetry-php
> update quoteservice to opentelemetry-php beta

- README.md
Add Grafana Labs' fork as a vendor fork to README
> Add Grafana Labs' fork as a vendor fork to README

- CHANGELOG.md
- docs/services/cartservice.md
- src/cartservice/src/Program.cs
- src/cartservice/src/cartservice.csproj
Resource detection for cart service, right now it is only the container.id because it looks like no other resource detectors exist for .NET (yet)
> Add resource detectors to cart service

- CHANGELOG.md
- docs/services/checkoutservice.md
- src/checkoutservice/main.go
Similar to #648 & #651 this adds more resources being detected to the checkout service.
> Add resource detection to checkout service

- src/featureflagservice/Dockerfile
I tested v1.1-v1.2.1 on M1 and x86/Linux. I was able to recreate issue #696 on all versions that included OTP 25.
> Fixes #696, Downgrades OTP

- .github/PULL_REQUEST_TEMPLATE.md
For some reason the link to docs is not working:
I've updated the template to use the link of the docs page itself, instead of a reference to it.
> Fix link to the docs

- CHANGELOG.md
- src/adservice/Dockerfile
Minor change for the adservice: Similar to frauddetectionservice this makes use of the gradle image to save some time downloading gradle (since both use the same gradle image then this even saves some extra time downloading the image). It also replaces the jdk with a jre image for the final image, saves some ~190MB (518 down to 328)
> Update dockerfile for adservice to use different base images

- CHANGELOG.md
- docker-compose.yml
- docs/demo_features.md
- docs/metric_service_features.md
- src/grafana/provisioning/dashboards/general/demo-dashboard.json
- src/grafana/provisioning/datasources/default.yaml
- src/otelcollector/otelcol-config.yml
* Ensure the collector's Prometheus endpoint produces exemplars 
* Ensure that Prometheus collects and stores exemplar data
* Ensure that Grafana will display links to exemplars from dashboards/the explore tab
[docs](https://github.com/open-telemetry/opentelemetry-demo/tree/main/docs) folder
> Enable exemplar export/display support

- .env
Remove the `v` prefix from the image version. We now publish images without this prefix.
Without this `docker compose build` will not work.
> [chore] - fix image version

- docker-compose.yml
- docs/demo_features.md
Adds caveats to current exemplar support in the demo architecture
Also, updates collector version: exemplars for the latency histogram produced by the span  metrics processor are now getting exported for all services and endpoints, not just the first one in the metric family.
[docs](https://github.com/open-telemetry/opentelemetry-demo/tree/main/docs) folder
> Adds caveats to current exemplar support in the demo architecture

- src/otelcollector/otelcol-config.yml
Temporarily add a transform processor to ensure that all `http.server.duration` metrics have the same description before being exported by Prometheus.  Fixes #737.
> Ensure all http.server.duration metrics have the same description

- README.md
- package-lock.json
- Closes #742
- Adds OTel logo, fetched from [opentelemetry.io], back to the title (level 1 heading) of the README.md file
- No `CHANGELOG.md` entry required, I suppose :).
[opentelemetry.io]: https://opentelemetry.io/docs/demo/
/cc @cartersocha
> Add OTel logo to README

- CHANGELOG.md
- pb/demo.proto
- src/accountingservice/kafka/consumer.go
- src/adservice/README.md
- src/adservice/build.gradle
- src/adservice/src/main/java/oteldemo/AdService.java
- src/cartservice/src/cartstore/ICartStore.cs
- src/cartservice/src/cartstore/LocalCartStore.cs
- src/cartservice/src/cartstore/RedisCartStore.cs
- src/cartservice/src/services/CartService.cs
- src/cartservice/tests/CartServiceTests.cs
- src/checkoutservice/main.go
- src/checkoutservice/money/money.go
- src/checkoutservice/money/money_test.go
- src/currencyservice/proto/demo.proto
- src/currencyservice/src/server.cpp
- src/featureflagservice/config/runtime.exs
- src/featureflagservice/rebar.config
- src/frauddetectionservice/src/main/kotlin/frauddetectionservice/main.kt
- src/paymentservice/index.js
- src/productcatalogservice/main.go
- src/shippingservice/src/shipping_service.rs
- test/test.js
Renames the proto definition package to oteldemo. Wanted to see how much work was involved here, open to alternative names. Figured oteldemo was short and to the point :)
Fixes #638
> rename proto package from hipstershop to oteldemo

- src/prometheus/prometheus-config.yaml
OTel Collector exports `/metrics` with `job` label set. However, if we run Prometheus with `honor_labels: false` (default), it will ignore the `job` label and set it to `job=otel, exported_job=recommendation-service`.
This is literally the case for which `honor_labels` was created and it should be set to true, which will make sure that the final metrics in Prometheus will have only `job=recommendation-service`
> prometheus: honor_labels to have the right job and instance

- CONTRIBUTING.md
Just a nit fix noted while trying to contribute here!
> Nit fix contributing guide

- CHANGELOG.md
- src/cartservice/src/Program.cs
Removed unnecessary API calls and added await.
> Clean up Program.cs

- CHANGELOG.md
- src/adservice/src/main/java/oteldemo/AdService.java
- src/emailservice/Gemfile.lock
- src/recommendationservice/requirements.txt
Minor updates to work with Mac M2 architectures.
- adservice/AdService.java - IntelliJ gave an error without the package prefix.
- emailservice/Gemfile.lock - Add arm64-darwin-22
- recommendationservice/requirements.txt - grpcio update required to work with M2 [[ref](https://github.com/grpc/grpc/issues/30182)]
> [chore] update for mac m2

- CHANGELOG.md
After we release we need to get the changelog updated to move all items from `Unreleased` into a new section for the release (1.3.1)
> [chore] - finalize 1.3.1 changelog

- CHANGELOG.md
- src/frontend/components/CartItems/CartItems.tsx
This fixes the shipping cost update when any parameters (like list of products) for the shipping API call change.
The `react-query` component needs a unique key to know whether to make a network call or use cached data. The query parameters are used as a unique key. This is documented [here](https://react-query-v3.tanstack.com/guides/query-keys#if-your-query-function-depends-on-a-variable-include-it-in-your-query-key).
The original bug is listed in https://github.com/open-telemetry/opentelemetry-demo/issues/327
> Fix shipping cost update when new item is added to cart 

- .yamlignore
Use an absolute path for yamllint ignore to unblock #791
> [chore] use absolute path for yamllint

- .yamlignore
- Makefile
In the never-ending quest to get #791 to pass yamllint checks
Turns out that locally on my system, I have `yamllint` installed with brew, which grabs the latest version (currently 1.30.0). The GH check (via our Makefile) installs this using pip, which specifies version 1.26.3.  We use a yamllint config option of `ignore-from-file`, which was introduced in 1.28.0, and hence that's why it wasn't working.
This PR updates the yamllint version to the latest version (1.30.0)
> [chore] use yamllint 1.3.0

- src/cartservice/NuGet.config
- src/cartservice/src/Program.cs
Use explicit package source(s) for NuGet (best practice).
Sort the namespaces (best practice).
> Cart Service - minor cleanup

- CHANGELOG.md
- src/frontend/components/Footer/Footer.styled.ts
- src/frontend/components/Footer/Footer.tsx
- src/frontend/components/Layout/Layout.tsx
- src/frontend/components/PlatformFlag/PlatformFlag.styled.ts
- src/frontend/components/PlatformFlag/PlatformFlag.tsx
Moved the env flag the the bottom right corner of the footer. I also removed the environment enum, so the text in the flag can be anything. The implication, however, is that the background color will be the same for any value.
Addresses https://github.com/open-telemetry/opentelemetry-demo/issues/616
> Updated ENV_PLATFORM flag

- docker-compose.yml
For now, `prometheus` service starts with exemplar-storage feature, which has bugs in v2.34.0 version, caused the manually added metric `app.ads.ad_requests` in service `adService` can not be scraped successfully. 
The error detail in prometheus [target status page](http://127.0.0.1:9090/targets?search=), 
| metric name app_ads_ad_requests does not support exemplars
This is known [issue](https://github.com/prometheus-net/prometheus-net/issues/407) in prometheus community  and be  resolved in [pr](https://github.com/prometheus/prometheus/pull/11984), which is release in v2.43.0
> [prometheus] fix prometheus scrape bug

- CHANGELOG.md
- docker-compose.yml
- src/grafana/provisioning/dashboards/general/spanmetrics-dashboard.json
- src/otelcollector/otelcol-config.yml
I would suggest updating opentelemetry-demo to use the [spanmetrics connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector) instead of the [spanmetrics processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanmetricsprocessor), as the latter has been deprecated. 
By doing this we can also let user to take advantage of the new advanced functionality `connector`.
I also modify the spanmetric dashboard to be compatible with breaking changes from the spanmetrics connector, which are listed in (here)[Compatibility with important changes to the Spanmetrics connector
]
[docs]: …
> [collector] use spanmetrics connector instead of spanmetrics processor

- src/cartservice/src/Program.cs
After #835 got merged, I saw that we could get rid of `.SetResourceBuilder(appResourceBuilder)` which is being used twice (Tracing and Metrics), in favor of `ConfigureResource`.
I already have an opened PR to update the cartservice docs, I can update it, whenever this gets merged:
https://github.com/open-telemetry/opentelemetry.io/pull/2607
> [cartservice] - Use ConfigureResource

- .env
- CHANGELOG.md
- Makefile
- kubernetes/opentelemetry-demo.yaml
With a Helm chart released for 1.4 of the demo, this is an output of that release. Also forces the namespace to be `otel-demo` and when combined with a docs change will fix #840
> [chore] update kubernetes manifest

- CHANGELOG.md
- src/currencyservice/Dockerfile
Fix #885.
Added `-DCMAKE_CXX_STANDARD=17` to the `cmake` command and updated OTel version to `1.9.0`
> [currencyservice] Fix OTel C++ build and update OTel version

- CHANGELOG.md
- src/cartservice/src/Program.cs
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
Fixes: #918
Update .NET OTel to 1.5.0 together with other related and unrelated dependencies.
* ~~[ ] Appropriate Helm chart updates in the [helm-charts][]~~ I do not found anything to update
> [cartservice] Update .NET OTel to 1.5.0

- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
Update target and docker images to .NET7 for cartservice.
* ~~[  ] Appropriate Helm chart updates in the [helm-charts][]~~ N/A
> [cartservice] Update to .NET 7

- src/shippingservice/Cargo.lock
In #972 I forgot to push the `cargo.lock` file
> shippingservice-missing-cargolock-update

- CHANGELOG.md
- docker-compose.minimal.yml
New frontendproxy's code use a new set of variable OTEL_COLLECTOR_PORT_GRPC & OTEL_COLLECTOR_PORT_HTTP to replace the old OTEL_COLLECTOR_PORT. But we miss update this in docker-compose.minimal.yml setup
> fix: update frontendproxy's env  for minimal

- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
This should fix the intermittent build errors in GHA
> Roll cart service back to .NET 6

- src/adservice/Dockerfile
- src/adservice/build.gradle
- src/adservice/gradle/wrapper/gradle-wrapper.properties
- src/adservice/src/main/java/oteldemo/AdService.java
> Update AdService Dependencies

- docker-compose.yml
This PR removes an unused env var from docker compose, addressing an issue described here: https://github.com/open-telemetry/opentelemetry-demo/pull/984#pullrequestreview-1535464039
> fix(tests): removing unused env var on trace-based tests

- src/otelcollector/Dockerfile
Updated the OTel Collector `Dockerfile` to resolve this bug: https://github.com/open-telemetry/opentelemetry-demo/issues/1013
> TARGETARCH cannot have a default value, and set GOARCH similarly

- .github/workflows/gradle-wrapper-validation.yml
https://github.com/open-telemetry/opentelemetry-demo/pull/1015 had some EasyCLA issues, I've closed it and sent this PR manually.
> wrapper-validation-action from 1.0.6 to 1.1.0

- CHANGELOG.md
- test/tracetesting/checkout-service/place-order.yaml
- test/tracetesting/frontend-service/06-checking-out-cart.yaml
Fix: #1091.
After #1083 being merged, some attributes for the Kafka spans have changed and the TraceTests needed to be adapted.
> Fix TraceTest after IBM/sarama upgrade

- README.md
This PR updates the readme.
It adds Tracetest to the table of demos featuring the astronomy shop
> readme: add Tracetest to demos featuring the astronomy shop

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- kubernetes/opentelemetry-demo.yaml
- src/quoteservice/Dockerfile
- src/quoteservice/README.md
- src/quoteservice/app/dependencies.php
- src/quoteservice/app/routes.php
- src/quoteservice/composer.json
- src/quoteservice/public/index.php
- update dependencies to use RC1 and latest versions of other packages
- update code to work with RC1
- refactor Dockerfile to allow local dev, and document how
> update quoteservice for php Release Candidate

- src/loadgenerator/requirements.txt
#1128 also requires updating the Werkzeug package to get it compiling.
> Required werkzeug update

- CHANGELOG.md
- Makefile
- docker-compose.yml
- src/frontendproxy/Dockerfile
- src/kafka/Dockerfile
Updates version for all dependent components:
- postgres
- kafka
- redis
- grafana
- jaeger
- prometheus
- opentelemetry-collector
- envoy
Where possible, I locked to minor versions instead of patch versions. The alpine variant is used for redis because it significantly reduces container size, but not for other components.
While doing all this, I found myself wanting a `make build` target, which is also included in this PR.
> (chore) update dependency versions

- src/otelcollector/otelcol-config.yml
Adds a filter to drop the `rpc.server.duration` metric due to high cardinality on this metric in the Go SDK, which causes downstream memory problems in the collector and Prometheus. We should remove this filter definition after implementing a Metrics View for the checkout and productcatalog services, or this [PR](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3730) on the Go SDK is merged, released, and incorporated into the demo.
Adds a transform to clear the description for the `http.client.duration` metric. This is required to eliminate errors with the Prometheus exporter in the collector. There is a [PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1959) at the Python SDK level to fix this, but that fix will take some time before it's released …
> (otelcol): metrics filter and transform

- CHANGELOG.md
- docker-compose.yml
- src/otelcollector/otelcol-observability.yml
Fixes #1143 
Prometheus now supports push with the OpenTelemetry Protocol OTLP. This PR enables that supports and moves away from the `prometheus` exporter in favor of the `otlphttp` for metrics export to Prometheus.
> (prometheus) Add OTLP write support

- .env
- CHANGELOG.md
- Makefile
- docker-compose.yml
- test/tracetesting/Dockerfile
Added an env var to make sure the same image version is used for the trace-based test tool. Currently the image version pin in the `tracetesting/Dockerfile` differs from the image version pin in the `docker-compose.yaml`.
Updated docs in this PR: https://github.com/open-telemetry/opentelemetry.io/pull/3526
> chore: add env var for pinning trace-based test tool version

- src/shippingservice/Dockerfile
fixes #1240
Updated builder image `rust:1.73` is now based on debian bookworm ([dockerhub link](https://hub.docker.com/layers/library/rust/1.73/images/sha256-e5a28b9e772535dc50205b4684b4e1cd113bb52e02e54ff387015c55c561e477?context=explore)). The fix matches the release image accordingly.
> Shippingservice: update release image to match builder

- src/featureflagservice/lib/featureflagservice_web.ex
- src/featureflagservice/lib/featureflagservice_web/templates/feature_flag/form.html.heex
- src/featureflagservice/lib/featureflagservice_web/templates/layout/app.html.heex
- src/featureflagservice/lib/featureflagservice_web/templates/layout/root.html.heex
- src/featureflagservice/mix.exs
Phoenix 1.7 has deprecated Phoenix.View in favor
of Phoenix.Component and moved the get_flash
function out of controllers, making us call it
directly
This is an addendum to #1224
> use Phoenix 1.6 style

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- test/tracetesting/Dockerfile
This PR fixes the CLI version in `test/tracetesting/Dockerfile` to use the env variable that was added as part of https://github.com/open-telemetry/opentelemetry-demo/pull/1239. This guarantees the use of the same image version for the tracetest server and CLI in the trace-based process. 
> fix: pass proper env var to tracetesting Dockerfile

- .github/workflows/build-images.yml
- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
Update cartservice to .NET8 which is new LTS release.
Replaces #1269
Fixes #1262
> [cartservice] Update to .NET8

- src/grafana/provisioning/dashboards/demo/opentelemetry-collector-data-flow.json
- src/prometheus/prometheus-config.yaml
This fixes #1292 which was introduced by #1174 
The original PR removed the `otel-collector` scrape job from Prometheus, shutting off Collector meta-metrics. This re-introduces it and updates the collector monitoring dashboard to reference the new job.
> Re-add prometheus collector metric scrape

- src/currencyservice/Dockerfile
This PR fixes the currencyservice build failure; We also need to update some flags to handle the updated protobuf libraries.
> update cpp and pin to 3.18

- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
A number of simplifications to the cartservice Dockerfile.
1. Per https://github.com/dotnet/dotnet-docker/pull/4742, it is an anti-pattern to use msbuild properties in a Dockerfile. The properties are now set in the csproj file. 
3. Removed `-c Release` from `dotnet publish` command. As mentioned in [this blog post](https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/) it is now the default.
4. Simplified determining the runtime identifier. The `-r` switch now translates `linux-musl-amd64` to `linux-musl-x64` under the covers. See https://github.com/dotnet/sdk/issues/30369.
> Simplify cartservice Dockerfile

- docker-compose.minimal.yml
- docker-compose.yml
Fixed #1309 
Reverts the version of Grafana back to 10.2.0. Seems like the latest version has an issue starting up with our config.
> [chore] - revert grafana to 10.2.0

- CHANGELOG.md
- src/cartservice/src/Dockerfile
Fixes: #1310 
Disables config reload within the docker container.
> [cart] - disable reload config

- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
1. Update OTel .NET SDK to 1.7.0 and other OTel released packages.
2. Update other .NET dependencies
3. Bump docker images for .NET to mitigate security issues. - ref https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.1/8.0.1.md
[helm-charts]: …
> [cartservice] Bump OTel .NET SDK to 1.7.0 together with other dependencies

- CONTRIBUTING.md
- src/accountingservice/README.md
- src/checkoutservice/README.md
- src/productcatalogservice/README.md
Uses the proper GitHub Markdown syntax to indicate notes, warnings, etc.
```
> [!NOTE]
> my note
```
This is the before and after for the change.
before:
after:
> [chore] - use GitHub markdown syntax in docs

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- src/frontendproxy/Dockerfile
- src/frontendproxy/envoy.tmpl.yaml
This enables the environment resource detector for the envoy opentelemetry tracer. See https://github.com/envoyproxy/envoy/pull/29547
> [frontendproxy] enable envoy environment resource detector

- CHANGELOG.md
- src/currencyservice/src/meter_common.h
Fixes #1330
Sets the OTLP metric export temporality to be cumulative (default), similar to other services. Sets the MetricReader to export every 60 seconds (default), similar to other services. 
I left the lines of code to change the options in as comments set to their default values, so other users can see what the options objects are used for.
> [currency] - fix metricreader export and temporality

- CHANGELOG.md
- internal/tools/tools.go
- src/accountingservice/tools.go
- src/checkoutservice/tools.go
- src/productcatalogservice/tools.go
This pull request updates the URLs for the Go wiki, which has been moved from GitHub Wiki to go.dev. The previous URLs were broken due to this relocation.
> Update wiki url

- CHANGELOG.md
- src/adservice/Dockerfile
- src/frauddetectionservice/Dockerfile
Changed file access permission (chmod 644 instead of the default 600) for opentelemetry-javaagent.jar as it gets copied into the docker image for services adservice and frauddetectionservice.
This is done for the case where the containers are executed in a secure environment that has `runAsRoot: false` enforced.  In such cases, the user `nobody` didn't even have read access to the mentioned jar, causing crashlooping for the two mentioned services.
* ~Appropriate documentation updates in the [docs][]~
* ~Appropriate Helm chart updates in the [helm-charts][]~ …
> Fix crashlooping for two services with insufficient privileges on opentelemetry-javaagent.jar.

- .env
- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
Update dependent services - Collector, Grafana, Jaeger, Prometheus, etc.
Move those external service image paths and versions to `.env` file to make it easier to update them for multiple docker compose files.
> Update dependent services - Collector, Grafana, Jaeger, Prometheus, etc.

- .github/workflows/run-integration-tests.yml
This PR ensures that the instance cleanup job will always run
>  always run cleanup job

- .github/workflows/run-integration-tests.yml
- .gitignore
- CHANGELOG.md
- Makefile
- test/tracetesting/cart-service/add-item-to-cart.yaml
- test/tracetesting/cart-service/check-if-cart-is-empty.yaml
- test/tracetesting/cart-service/check-if-cart-is-populated.yaml
- test/tracetesting/cart-service/empty-cart.yaml
- test/tracetesting/currency-service/convert.yaml
- test/tracetesting/currency-service/supported.yaml
- test/tracetesting/frontend-service/04-add-product-to-cart.yaml
- test/tracetesting/frontend-service/05-view-cart.yaml
Fixes traced based tests alerts to use new attribute name and values to reflect changes in the services to properly support semantic conventions.
This also adds `.PHONY` designation to the make targets for tests, and comments out unused (and failing) integrationTests. The integrationTests test should be removed in another PR.
> [chore] fix trace tests

- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
[cartservice] Bump .NET to 8.0.2 together with other package dependencies.
It contains security fixes for .NET.
> [cartservice] Bump .NET to 8.0.2

- README.md
Adds link to GCP fork of the demo to the vendors table.
As a side note, I couldn't tell if this is supposed to be generated or not so I did it by hand. It would be nice if there was a make command or something to generate the table from the list of links.
> Add Google Cloud fork to demos list

- src/checkoutservice/main.go
> refactor(checkoutservice): reuse grpc service client

- .env
- docker-compose.minimal.yml
- docker-compose.yml
This depends on #1398 being merged and a set of nightly images being published successfully.
This will fix #1393
Introduces a new environment variable called `DEMO_VERSION`, which is set to `latest`. This will be used in docker-compose.yml to use the latest (re: nightly) release. If a user wants to lock it to a specific version, they can update and use this environment variable. Builds will still cache from the prior release to keep build times low.
[docs]: …
> [chore]: use nightly releases

- src/frontend/package-lock.json
- src/frontend/package.json
Building the frontend container image on an Apple M1 would result in the following error during docker build:
15.56 > Build error occurred
15.56 [Error: ENOENT: no such file or directory, copyfile '/app/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node' -> '/app/.next/standalone/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node'] {
15.56   errno: -2,
15.56   code: 'ENOENT',
15.56   syscall: 'copyfile',
15.56   path: '/app/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node',
15.56   dest: '/app/.next/standalone/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node'
15.56 }
Updating sharp to v0.33.x avoids this problem, as that version includes pre-built sharp binaries for various platforms, see https://sharp.pixelplumbing.com/changelog#v0330---29th-november-20 …
> [frontend] update sharp to latest to avoid docker build issue on M1

- src/frontend/gateways/rpc/Shipping.gateway.ts
[frontend] fix typo in ShippingGateway
> [frontend] fix typo in ShippingGateway

- README.md
Adding the Liatrio demo fork to the list of vendor demos based on conversation
with Demo SIG.
> [chore] add Liatrio to list of vendor demos

- .env
- .gitignore
- CHANGELOG.md
- src/currencyservice/src/server.cpp
- src/grafana/provisioning/datasources/opensearch.yaml
This PR updates Telemetry Components to latest version.
> Update Telemetry Components

- src/accountingservice/Dockerfile
- Use `golang:1.22-alpine` instead of `golang:1.22.x-alpine` to always get the latest patch version. (i.e: currently golang:1.22-alpine will resolve the go version: 1.22.1 (latest))
- Use mount type=cache and type=bind from buildkit spec (this is also suggested by command `docker init`) for better performance when running `docker build`.
- Use `go list` command to install go tools in tools.go with versions locked in go.mod
[helm-charts]: …
> refactor(accountingservice): refactor accountingservice dockerfile

- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
- test/tracetesting/checkout-service/place-order.yaml
[cartservice] update .NET to .NET 8.0.3 together with other packages.
It is security release from MS.
> [cartservice] update .NET to .NET 8.0.3

- Makefile
Fix #1459
`/feature` was removed with the FeatureFlag custom service we had.
We are now using `flagd` which doesn't have an endpoint.
> remove reference of featureflag endpoint

- CHANGELOG.md
- src/frontendproxy/envoy.tmpl.yaml
Removes a deprecated option from the Envoy config. This removes the following warning from the frontend-proxy logs on startup. 
```
frontend-proxy  | [2024-03-19 18:00:53.063][8][info][tracing] [source/common/tracing/tracer_manager_impl.cc:42] instantiating a new tracer: envoy.tracers.opentelemetry
frontend-proxy  | [2024-03-19 18:00:53.063][8][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.extensions.filters.http.router.v3.Router Using deprecated option 'envoy.extensions.filters.http.router.v3.Router.start_child_span' from file router.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely …
```
> remove deprecated start_child_span option

- CHANGELOG.md
- src/frontend/utils/telemetry/Instrumentation.js
Fixes #1468 
The `instrumentaion-fs` library was generating 2 spans for nearly every GET request into the frontend. Since we now use a playwright enabled loadgenerator, this was happening for every resource being loaded, leading to a much larger load and additional noise being generated. Disabling the library removes that noise.
This chart is a count of spans for the frontend service by name before and after the change in this PR was deployed.
[docs]: …
> [frontend] - disable fs instrumentation library

- CHANGELOG.md
- src/currencyservice/src/server.cpp
We broke the metric name in #1378. This fixes that name and sets it to `app.currency.counter.total` as it was before.
> [currency] - fix metric name

- src/adservice/src/main/java/oteldemo/AdService.java
When the [adServiceFailture](https://opentelemetry.io/docs/demo/feature-flags/) feature flag is enabled, AdService returns a `RESOURCE_EXHAUSTED = 8` grpc status code. This does not result in the span status being set to error according to the grpc semantic conventions: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/grpc.md
Updating to return `UNAVAILABLE = 14` so that span status is reflected as error as the feature flag implies.
Side note: The docs site says that when this feature flag is enabled, an error is generated 1/10th of the time. I don't see any code that would limit this to only 10% of the time. Maybe I'm missing something.
> Adservice returns error status code when feature flag is enabled

- docker-compose.yml
- src/kafka/Dockerfile
- Use official image `apache/kafka` (ref: https://cwiki.apache.org/confluence/display/KAFKA/KIP-975%3A+Docker+Image+for+Apache+Kafka)
- Upgrade otel java instrumentation.
> chore(kafka): use apache/kafka official image

- CHANGELOG.md
- src/frontend/utils/enums/AttributeNames.ts
- src/frontend/utils/telemetry/InstrumentationMiddleware.ts
This reunites the trace when initiated from the load generator. Now that #1501 is merged, we have span links done from a Kafka consumer service. Making this 1 trace will remove confusion from people looking to see the load from the load generator, only to see it broken up into multiple traces.
> [frontend] reunite trace from loadgenerator

- .github/workflows/build-images.yml
- CHANGELOG.md
Adds the Trace Based Tests image with our build and published image set. This is the only image built in the demo locally that we do not publish.
Fixes: #993 
> [repo] add traceBasedTests image

- test/tracetesting/frontend-service/06-checking-out-cart.yaml
This PR updates the TraceTest, as `frauddetection` is not part of the checkout anymore.
I've reached out to the TraceTest team to see if we can validate linked traces somehow, but as of now, we can remove the test.
The trace path was changed on this PR: #1501
> [chore] Update frontend test to remove fraud detection span check

- CHANGELOG.md
- src/quoteservice/app/routes.php
- src/quoteservice/app/settings.php
- src/quoteservice/composer.json
- src/quoteservice/public/index.php
- test/tracetesting/shipping-service/quote.yaml
- add a manual metric to the php quote service
- randomize per-item cost to add some variability to quotes
- bump dependencies to latest
- fix a monolog deprecation
- ensure logs are exported per the configured delay
> [quoteservice] manual metrics, logs export

- src/adservice/Dockerfile
As described in Docker [docs](https://docs.docker.com/reference/dockerfile/#copy):
> If multiple <src> resources are specified, either directly or due to the use of a wildcard, then <dest> must be a directory, and it must end with a slash /.
Having no slash at the end of this command may make Docker build fail under certain circumstances.
Adds `/` to Dockefile in `adService`
[helm-charts]: …
> Append slash to copy destination in adService Dockerfile

- CHANGELOG.md
- src/frontend/components/CheckoutItem/CheckoutItem.tsx
This fix addresses the missing image problem in https://github.com/open-telemetry/opentelemetry-demo/issues/1525
> [frontend] Pass down image optimization requests to imageprovider in checkoutitem component

- CHANGELOG.md
- src/otelcollector/otelcol-config.yml
- Add `redisreceiver` for demonstration.
> feat(otelcol): add redisreceiver

- CHANGELOG.md
- docker-compose.yml
- src/checkoutservice/main.go
- src/flagd/demo.flagd.json
- src/frauddetectionservice/build.gradle.kts
- src/frauddetectionservice/src/main/kotlin/frauddetectionservice/main.kt
This PR adds a new feature flag `kafkaQueueProblems` to the opentelemetry demo. Upon activating the feature flag, the producer (`checkoutservice`) overloads Kafka by sending 100 extra messages to the queue per actual order. Simultaneously, the consumer (`frauddetectionservice`) delays the claiming of the messages by 1 second per message. This leads to a sudden spike in consumer lag. This is an interesting, real world observability scenario because it simulates queue problems in kafka which afaik no feature flag does yet. Metrics that monitor consumer lag can be viewed in Grafana (e.g. `kafka_consumer_lag_avg`). 
Also increased the resource limitations of the frauddetection service since it kept dying due to resource exhaustion. This also happened without my modifications to the service. …
> [kafka][checkoutservice][frauddetectionservice] add kafkaQueueProblems featureflag

- src/adservice/src/main/java/oteldemo/AdService.java
- src/flagd/demo.flagd.json
- src/frontend/gateways/Api.gateway.ts
- src/frontend/utils/telemetry/FrontendTracer.ts
- src/loadgenerator/locustfile.py
Automatically adds session information to baggage for all requests from the browser and synthetic tests. This information is then used in downstream services as part of the feature flag evaluation context. The AdService has also been updated to leverage this change.
> Consistent baggage propagation

- .env
- CHANGELOG.md
- docker-compose.yml
- test/tracetesting/Dockerfile
Fixes #1550 
Since the tracetest server and CLI version need to match, we must ensure both images are aligned. The solution is to hardcode the tracetest version in the GitHub workflow or the Dockerfile. I opted to specify this in the Dockerfile, adding a comment on why we need to do it there.
> [chore] specify default value for tracetest image version

- .github/workflows/build-images.yml
Fixes: #1547 
Adds imageprovider to the build-images workflow. Also, I cleaned up the order of each image to be alphabetical based on tag suffixes.
> [imageprovider] - add image to build-images workflow

- .env
> chore(deps): upgrade otel collector contrib, grafana and prometheus

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- src/flagd/demo.flagd.json
- src/frontend/components/ProductCard/ProductCard.tsx
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/pages/_app.tsx
- src/frontendproxy/envoy.tmpl.yaml
Add FeatureFlag Provider to client side.
Add http fault filter to envoy
Add slowloading featureflag, and modify the Product card element to disable caching and add the envoy http-fault header
Example of a slowly loaded image trace:
> [frontend] Slowloading of images

- CHANGELOG.md
- src/kafka/Dockerfile
Before the fix, kafka will crash immediate when running in docker compose on m1 mac, unsure if this also happens in other environments or platform.
How to reproduce the issue
```
docker compose up --no-deps --build kafka
```
logs
```
kafka  | Error opening zip file or JAR manifest missing : /tmp/opentelemetry-javaagent.jar Error occurred during initialization of VM agent library failed Agent_OnLoad: instrument
kafka exited with code 1
```
inspecting the jar showing incorrect permission
```
/ $ ls -al /tmp/opentelemetry-javaagent.jar 
-rw-------    1 root     root      21007939 Apr 12 00:45 /tmp/opentelemetry-javaagent.jar
```
after the fix
```
/ $ ls -al /tmp/opentelemetry-javaagent.jar 
-rw-------    1 appuser  appuser   21007939 Apr 12 00:45 /tmp/opentelemetry-javaagent.jar
```
For new …
> Fix kafka permission in dockerfile

- CHANGELOG.md
- src/cartservice/src/cartservice.csproj
Bump cartservice .NET dependencies to 1.8.1
> [cartservice] bump Otel .NET SDK to 1.8.1

- CHANGELOG.md
- docker-compose.minimal.yml
Fixes: https://github.com/open-telemetry/opentelemetry-demo/issues/1583
> add flagd service to minimal docker compose

- CHANGELOG.md
- docker-compose.yml
Fixes: #1544 
Increases Kafka memory and Java Heap settings. This is similar to a change that was done on the [Helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1173). 
* ~[ ] Appropriate documentation updates in the [docs][]~
> [kafka] increase kafka memory limits

- .github/workflows/component_build-images.yml
The `config-inline` parameter is deprecated, and we should use `buildkitd-config-inline` instead. See this [PR](https://github.com/docker/setup-buildx-action/pull/303) for more details.
This is the warning message in our GHA for build and publish.
> [chore] update buildx config

- kubernetes/opentelemetry-demo.yaml
With the Helm chart for 1.10.0 released, we can update the K8s manifests too.
`make generate-kubernetes-manifests` 
* ~[ ] `CHANGELOG.md` updated to document new feature additions~
* ~[ ] Appropriate documentation updates in the [docs][]~
* ~[ ] Appropriate Helm chart updates in the [helm-charts][]~
> [chore] update k8s manifests 1.10.0 release

- CHANGELOG.md
We did not update the changelog heading accordingly when releasing 1.10.0. This fixes that.
> [chore] - update changelog to 1.10.0 release

- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/Program.cs
- src/cartservice/src/cartservice.csproj
- src/cartservice/tests/cartservice.tests.csproj
[cartservice] Bump OTel .NET SDK to 1.9.0 together with other dependencies
> [cartservice] Bump OTel .NET SDK to 1.9.0

- .env
- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- src/cartservice/README.md
- src/cartservice/src/Program.cs
- src/cartservice/src/cartstore/ValkeyCartStore.cs
- src/otelcollector/otelcol-config.yml
This PR replaces Redis with Valkey.
Redis has recently changed its licensing and Valkey was created by the community to continue the project as an Open Source driven project.
[Valkey/about](https://valkey.io/about/):
> The transition garnered substantial backing from leading tech corporations including AWS, Google, Oracle, Ericsson, and Snap, with the Linux Foundation stepping in to provide a stable platform for this new direction.
[Linux Foundation Launches Open Source Valkey Community](https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community).
which docs need to be changed …
> [Valkey] Replace Redis with Valkey

- CONTRIBUTING.md
This clarifies the entire release process as it is completed today.
We have plenty of opportunities to optimize this process, but I think it's important we properly document what needs to happen today so we can create a new demo release.
> [chore] clarify complete release process

- .env
- CHANGELOG.md
> [release] - update to 1.11.0 release

- kubernetes/opentelemetry-demo.yaml
Update k8s manifests to use the latest Helm chart with the Demo 1.11.0 release.
`make generate-kubernetes-manifests`
> [chore] update kubernetes manifests to 1.11.0 release

- README.md
Moves @austinlparker to Emeritus. Thank you, Austin, for everything you have contributed so far. We welcome your continued support as your time allows.
Adds @rogercoll to Approvers. Roger has been an active contributor and has provided valuable feedback on the success of the Demo project.
> [chore] update demo role memberships

- .env
- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- src/otelcollector/otelcol-config.yml
This PR adds the `docker_stats` receiver to the demo.
This receiver is meant to be used only when running locally on Docker.
For that to work we need privileged access to docker sock:
```yaml
user: 0:0
volumes:
- ${DOCKER_SOCK}:/var/run/docker.sock
```
I've also added Prometheus receiver to get internal Collector Metrics.
> [otel-col] Add docker stats receiver

- src/adservice/src/main/java/oteldemo/AdService.java
- src/cartservice/src/services/CartService.cs
- src/flagd/demo.flagd.json
Moved the random failure logic outside of the flag configuration and into the service. This simplifies the flag configuration and guarantees the behavior matches what's defined in [the docs](https://opentelemetry.io/docs/demo/feature-flags/).
- https://github.com/open-telemetry/opentelemetry-demo/issues/1628
> Simplify error scenario logic

- .env
- CHANGELOG.md
- docker-compose-tests_include-override.yml
- docker-compose.minimal.yml
- docker-compose.yml
- src/otelcollector/otelcol-config.yml
The default endpoints for all servers in the OTel Collector have changed to use localhost instead of 0.0.0.0.
If we keep the default, it won't work for Docker compose anymore.
> Set OTLP receiver endpoint

- CHANGELOG.md
- src/otelcollector/otelcol-config.yml
- adds a transform processor to the collector trace pipeline
- adds two rules for transforming span names:
- Strip anything after a "?"
- Replace productID with a token in "GET /api/products/{productID}" spans
~* [ ] Appropriate documentation updates in the [docs][]~
> Remove query params and product ID from span names

- .env
- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- src/otelcollector/otelcol-config.yml
This PR adds the hostmetrics receiver to the demo.
Related issue: https://github.com/open-telemetry/opentelemetry-demo/issues/1653
> [otel-col] Add host metrics receiver

- README.md
This PR adds Artifact Hub and OpenSSF badges to the main README.
OpenSSF was filled out by me and it is missing the Analysis section.
> [chore] Add Artifact Hub and OpenSSF badges

- docker-compose.minimal.yml
- docker-compose.yml
PR https://github.com/open-telemetry/opentelemetry-demo/pull/1683 broke Jaeger as https://github.com/jaegertracing/jaeger/releases/tag/v1.59.0 had a breaking change.
This PR adds the missing env var to Jaeger.
@puckpuck we need this env var before getting #1687 merged and released.
* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~
[helm-charts]: …
> Add required jaeger env var

- CHANGELOG.md
- Makefile
Add yamllint to `make all`, and adjust the logic for installing yamllint.
> chore: Add yamllint to `make all`

- .env
- docker-compose.yml
- kubernetes/opentelemetry-demo.yaml
Upgrade flagd to v0.11.2 to make it reload feature toggles properly.
Close #1625
> Upgrade flagd to v0.11.2

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/1722 
See https://github.com/docker/compose/issues/12139 (since Docker compose v2.29.6)
Bind mounts documentation: https://docs.docker.com/engine/storage/bind-mounts/#configure-bind-propagation
[helm-charts]: …
> fix: mount host filesystem as bind rslave mount

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
> [chore] Add depends on to otelcol to wait on healthy opensearch

- docker-compose.minimal.yml
- docker-compose.yml
`compose` and `compose.minimal` were different.
I've also validate it locally and with this test:
`curl -s http://localhost:9200/_cluster/health | grep status | grep -q '\\(green\\|yellow\\)'`
I was getting status `unhealthy` even though the `status:green` was there.
> [chore] streamline opensearch healthcheck

- src/productcatalogservice/main.go
Move the feature flag hook registration to the main method. This prevents the hook from being registered on every request.
This change brings the `product-catalog-service` in line with the `checkout-service`.
https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/checkoutservice/main.go#L163-L164
Resolves: #1735
> fix: only register otel during initialization

- CHANGELOG.md
- src/cartservice/src/Dockerfile
- src/cartservice/src/cartservice.csproj
- src/cartservice/src/services/CartService.cs
This PR changes the behaviour of `cartServiceFailure`.
When enabled, the `emptyCart`will fail 100% of the calls.
> [cartservice] Update cart service to fail when cartServiceFailure is enabled

- CHANGELOG.md
- src/cartservice/src/services/CartService.cs
Propagate Grpc expections; the `EmptyCart` method already sets the error in the span, but these two other methods aren't. A common propagated error is when the service cannot establish a connection with the Valkey database.
~~* [] Appropriate documentation updates in the [docs][]~~
> feat: propagate cartservice exceptions

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
This reverts commit a1cfe470c6c1e412865b351e473060b66674b2fb.
Annotations are not needed with latest Docker compose released version: https://github.com/docker/compose/releases/tag/v2.29.7
```
$ docker compose version
Docker Compose version 2.29.7
$ make start 2&> /dev/null && echo $?
docker compose --env-file .env --env-file .env.override up --force-recreate --remove-orphans --detach
OpenTelemetry Demo is running.
Go to http://localhost:8080 for the demo UI.
Go to http://localhost:8080/jaeger/ui for the Jaeger UI.
Go to http://localhost:8080/grafana/ for the Grafana UI.
Go to http://localhost:8080/loadgen/ for the Load Generator UI.
Go to http://localhost:8080/feature/ to to change feature flags.
0
```
For new features …
> Revert "fix: mount host filesystem as bind rslave mount (#1728)"

- Makefile
Let say that you add a `/src/adservice/Dockerfile.elastic` to the project to build a specific version of the image. So you add the following line to the `.env.override` file:
```env
AD_SERVICE_DOCKERFILE=./src/adservice/Dockerfile.elastic
```
If you run:
```sh
make redeploy
```
The `/src/adservice/Dockerfile.elastic` should be used instead of the default one.
This commit adds `DOCKER_COMPOSE_ENV` variable anywhere it's needed.
Closes #1758.
> Makefile does not always use `DOCKER_COMPOSE_ENV` var

- .env
- CHANGELOG.md
- Fixes an auth error, see https://github.com/grafana/grafana/issues/92634
> Bump Grafana version

- .env
- .github/workflows/component-build-images.yml
- CHANGELOG.md
- docker-compose-tests.yml
- docker-compose.minimal.yml
- docker-compose.yml
- src/adservice/Dockerfile
- src/currencyservice/Dockerfile
- src/frauddetectionservice/Dockerfile
- src/kafka/Dockerfile
- test/tracetesting/Dockerfile
Move `Dockerfile` build args to `.env` file
> [chore] Move build args to .env file

- docker-compose.minimal.yml
When using `make start-minimal` I was hitting an issue where the frontend-proxy container would start but then continually crash and restart with the following exception:
```
2024-11-06 17:03:02 [2024-11-06 22:03:02.686][8][critical][main] [source/server/server.cc:414] error initializing config '  envoy.yaml': Proto constraint validation failed (BootstrapValidationError.StaticResources: embedded message failed validation | caused by StaticResourcesValidationError.Clusters[5]: embedded message failed validation | caused by ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation | …
```
> Fix frontend-proxy crashing when using start-minimal

- README.md
This PR remove the Helios link from the "Demos featuring the Astronomy Shop" section.
[Snyk acquired Helios](https://snyk.io/blog/welcoming-helios-to-snyk/) and the link to showcase the demo is not available anymore.
Snyk and the team are more than welcome to add a new link later on, but the broken link is making the `markdownlint` check to fail.
The PR also simplifies the table, just adding a reference for the link.
* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~
which …
> Remove Helios from demo list

- CHANGELOG.md
- src/accountingservice/AccountingService.csproj
Bump OTel .NET Auto to 1.9.0 in accounting service.
> [accountingservice] Bump OTel .NET Auto to 1.9.0

- src/accountingservice/Dockerfile
- src/cartservice/src/Dockerfile
Fix #1798 - the issue is that the .NET Docker images are Debian based, however, the runtime identifier (RID) passed on the build step is targeting `musl` based distros, e.g.: Alpine. Fixing the RID avoids the error mentioned on #1798.
> Fix RUNTIME_IDENTIFIER for accountingservice

- .env
- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
- src/prometheus/prometheus-config.yaml
Update demo dependencies. The big change here is to Prometheus 3.x, which includes standard support for OTLP ingest.
> [chore] - update demo dependencies

- docker-compose.minimal.yml
- docker-compose.yml
- src/ad/Dockerfile
- src/ad/README.md
- src/ad/settings.gradle
- src/currency/CMakeLists.txt
- test/README.md
- test/tracetesting/ad/all.yaml
- test/tracetesting/currency/all.yaml
- test/tracetesting/recommendation/all.yaml
- test/tracetesting/run.bash
- test/tracetesting/shipping/all.yaml
This is the last piece needed to close out #1788 
removes the `-service` suffix from containers in docker-compose
removes the `-service` suffix from some containers in the trace test suite
removes `_SERVICE` from some environment variables used in the trace test suite
After these changes I ran `make run-tracetesting` and all tests completed successfully.
> [chore] remove -service and _service suffixes

- CHANGELOG.md
- src/flagd-ui/src/components/advanced/AdvancedView.tsx
Removed ES-Lint ignore comment in useEffect.
Refactored the useEffect inside the AdvancedView.tsx file, so that the required values are included in the dependency array (letting us remove the es-lint ignore comment) and requestSchemas function is memoized with useCallback (preventing unnecessary re-renders).
> flagd-ui refactor: fixed eslint ignore comment with useCallback

- CHANGELOG.md
- docker-compose.minimal.yml
- docker-compose.yml
Increase memory limits for
- frontend-proxy
- kafka
- grafana
- opensearch
Fix for #1831
After running the app for around 5 hours on Docker / Ubuntu / x86_64, I see the following memory usage:
```
$ docker stats --no-stream --format "table {{.Name}}\t{{.MemPerc}}\t{{.MemUsage}}" | sort -k 2 -h
NAME              MEM %     MEM USAGE / LIMIT
image-provider    4.34%     5.211MiB / 120MiB
recommendation    8.95%     44.77MiB / 500MiB
valkey-cart       17.68%    3.535MiB / 20MiB
shipping          18.91%    3.781MiB / 20MiB
currency          19.86%    3.973MiB / 20MiB
prometheus        30.72%    92.16MiB / 300MiB
frontend          39.31%    98.29MiB / 250MiB
quote             40.11%    16.04MiB / 40MiB
cart              41.37%    66.19MiB / 160MiB
email             47.32%    47.32MiB / 100MiB …
```
> Update memory limits

- .github/dependabot.yml
Dependabot PRs on docker are bumping versions to latest instead of LTS versions:
https://github.com/open-telemetry/opentelemetry-demo/pull/1900
There are a couple of issues asking for this feature on dependabot repo, but this doesn't seem to get any attention from the community: 
- https://github.com/dependabot/dependabot-core/issues/2247
- https://github.com/dependabot/dependabot-core/issues/2651
Dependabot can be configured to bump major, minor or patch version, but excluding major updates is not the same as updating just to LTS.
> [chore] Remove docker from dependabot

- src/accounting/Accounting.csproj
We are having issues building the accounting service, which was traced back to the Grpc.Tools version. This PR downgrades Grpc.Tools to 2.68.1.
After this change `docker compose build accounting` works as expected.
> [accounting] fix build

- CHANGELOG.md
- src/accounting/Accounting.csproj
[accounting] Bump OTel .NET Auto to 1.10.0 - https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v1.10.0
* ~~[ ] Appropriate Helm chart updates in the [helm-charts][]~~ N/A 
> [accounting] Bump OTel .NET Auto to 1.10.0

- src/cart/src/cart.csproj
[cart] Bump not-stable dotnet-contrib packages
* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~ N/A, it is not handled by dependabot for some reasons. I would skip it as in dependabot PRs.
> [chore] [cart] Bump not-stable dotnet-contrib packages

- src/frontend/Dockerfile
Currently, all the dev dependencies are included in the final image.
Reworking the first two stages, we can reduce the final image by ~15%
```
╰─➤  docker images otel-demo-frontend
REPOSITORY           TAG       IMAGE ID       CREATED          SIZE
otel-demo-frontend   fix       0a53d5f0fdcc   14 minutes ago   707MB
otel-demo-frontend   orig      a863b800e2ab   19 minutes ago   823MB
```
[helm-charts]: …
> [chore] frontend: update Dockerfile to reduce final image size by 15%

- CONTRIBUTING.md
Update the .env file before making a release. This way, when the new tag is added, the proper version will be included in the .env file. This allows people to cleanly pull a specific demo release and build against it as expected.
The downside is that if someone pulls from the main and tries to do a build after step 1 is complete but before step 2 is complete, they may have issues.
> [chore] clarify new release instructions

- Makefile
It adds a `clean-images` target, removing all demo images only. This is much less impactful to someone's system than running `docker system prune—a` when you are having issues with image cache.
> [chore] adds a clean-images Makefile target

- CHANGELOG.md
- src/frontend/Dockerfile.cypress
Fixes #1990 
Updates the base image for Cypress
> [frontend] Cypress Tests: update cypress/included to 14.0.3

- CHANGELOG.md
- src/frontend/utils/telemetry/FrontendTracer.ts
Fixes #2080 
Updates code to use updated semantic convention constant and use the `spanProcessors` option of the tracer provider, moving away from deprecated calls.
> [frontend] update browser tracer provider config

- CONTRIBUTING.md
- README.md
Updates the release process to add a final step: creating a tag with a `-k8s` suffix. This tag will contain Kubernetes manifests for the given release that are not part of the primary release's tag/branch.
> [chore] update release process

- src/load-generator/Dockerfile
Re-orders some build steps so Playwright is included before local code is copied. This allows docker to leverage cache for Playwright to perform faster builds between code changes.
> [load-generator] optimize build

- src/accounting/Accounting.csproj
- src/cart/src/cart.csproj
[chore] Bump .NET dependencies
- OTel SDK 1.11.2
- OTel .NET Auto 1.11.0
Handles https://github.com/open-telemetry/opentelemetry-dotnet/security/advisories/GHSA-8785-wc3w-h8q6
* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~ N/A, only package update
[helm-charts]: …
> Bump OTel .NET dependencies

- CHANGELOG.md
- src/quote/composer.json
Updated open-telemetry/exporter-otlp to 1.2.1 for PHP quote service (1.2.1 include fix for IS_REMOTE flag feature)
Updated open-telemetry/exporter-otlp to 1.2.1 for PHP quote service (1.2.1 include fix for IS_REMOTE flag feature - https://github.com/open-telemetry/opentelemetry-php/pull/1522)
* N/A - [ ] Appropriate documentation updates in the [docs][]
* N/A - [ ] Appropriate Helm chart updates in the [helm-charts][]
[helm-charts]: …
> [quote] Updated open-telemetry/exporter-otlp to 1.2.1 which includes the fix for IS_REMOTE flag feature

- CHANGELOG.md
- docker-compose.yml
> [flagd-ui] increase memory to 100M

- README.md
This PR adds SigNoz as another observability backend and links it to a blog, which helps get started with SigNoz using the OTel Demo App.
I've added SigNoz, as another option for an observability backend and linked it to a detailed blog, which helps setup SigNoz with the OTel Demo App. 
FYI:
[SigNoz](https://signoz.io/) is an OpenTelemetry-native observability backend and is completely open-source!
[helm-charts]: …
> Adds SigNoz as a observability backend to the README.md

- README.md
Adding [Last9](https://last9.io) as an o11y backend with link to the guide to send OTel demo data to Last9.
> add last9 as an o11y backend in readme

- CHANGELOG.md
- src/cart/src/cartstore/ValkeyCartStore.cs
Change custom app metrics from ticks to seconds and adds units for metrics.
[Per the .NET docs, `ElapsedTicks`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch.elapsedticks?view=net-9.0#remarks):
> ... represents the number of elapsed ticks in the underlying timer mechanism. A tick is the smallest unit of time that the Stopwatch timer can measure. Use the Frequency field to convert the ElapsedTicks value into a number of seconds.
Uses same bucket boundaries as [http.server.request.duration](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration) and [messaging.client.operation.duration](https://opentelemetry.io/docs/specs/semconv/messaging/messaging-metrics/#metric-messagingclientoperationduration) - happy to change this, …
> [cartservice] Record seconds instead of ticks for custom metrics

- src/shipping/Dockerfile
This PR updates the `shipping` service Dockerfile to use the latest `grpc-health-probe`. This also takes care of a few CVEs that are in this particular image.
> [shipping] update grpc-health-probe to latest

- .github/dependabot.yml
This PR updates the `dependabot.yml` file to include the various Dockerfiles in the OpenTelemetry Demo, so that they are using up to date image. This is in response to this discussion: https://github.com/open-telemetry/opentelemetry-demo/discussions/2147
> [chore] add Docker, Cargo, Bundler, .NET to Dependabot actions

- src/otel-collector/otelcol-config.yml
Updated collector telemetry push to OTLP/HTTP rather than OTLP/GRPC endpoint. 
Resolves issue https://github.com/open-telemetry/opentelemetry-demo/issues/2182. Also, I see Grafana dashboards is already updated to point to the new collector metrics over the deprecated ones. 
OTel collector has a bug in the telemetry push, even for un-authenticated otlp/grpc push the telemtery pusher is checking for TLS veirfication. More details here: https://github.com/open-telemetry/opentelemetry-collector/issues/12701
Updating the endpoint to OTLP/HTTP resolves the issue and the collector dashboards is populated with the required metrics in the Grafana dashboard:
> Update collector telemetry push to OTLP/HTTP

- CHANGELOG.md
- src/recommendation/Dockerfile
- src/recommendation/requirements.txt
This PR updates the Python based images to a `distroless` image as the final base image instead of the existing `slim-bookworm`. This results in a smaller image overall.
> [recommendation]: replace debian base image with alpine image

- CHANGELOG.md
- src/fraud-detection/Dockerfile
This PR updates the Python based images to a distroless image as the final base image instead of the existing `eclipse-temurin:21-jre` or deprecated distroless image. This results in a smaller image overall. It also updates the OTel Java Agent version to the latest version (`v2.15.0`).
> [fraud-detection]: update distroless image to latest

- CHANGELOG.md
- src/grafana/provisioning/dashboards/demo/demo-dashboard.json
- src/grafana/provisioning/datasources/opensearch.yaml
- src/otel-collector/otelcol-config.yml
This PR enhances the OpenTelemetry Collector configuration, Grafana data source, and Grafana dashboards to leverage dynamic index naming supported by the [OpenSearch exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/opensearchexporter) introduced in `opentelemetry-collector-contrib v1.29.0`.
Previously, all telemetry data was ingested into a single static index named `otel`. With this update, the index name is dynamically generated using a UTC-based timestamp format specified in the Collector configuration. For example, log data will now be indexed into time-partitioned indices such as `otel-logs-2025-07-15`.
Maintainers will not merge until the …
> [otel-collector] Add support for OpenSearch dynamic index

- README.md
Shenoy (@ps48) is an active contributor and member of the OTel Demo.
He is an active member on the SIG meetings and has contributions on the Demo: https://github.com/open-telemetry/opentelemetry-demo/issues?q=is%3Apr+author%3Aps48
This PR adds him to the list of Approvers.
> [chore] Add Shenoy to Demo Approvers

- .env
- CHANGELOG.md
Bump Flagd to [v0.12.8](https://github.com/open-feature/flagd/releases/tag/flagd%2Fv0.12.8) and get compliant `http.Server.request.duration` OTel metrics that can be used in the APM dashboard.
> Bump Flagd and get semconv compliant OTel metrics

- CHANGELOG.md
- src/cart/src/Program.cs
Resolves #2399 
Calls the `AddService` extension method for automatic generation of the `service.instance.id` attribute.
The `AddService` method has an argument named `autoGenerateServiceInstanceId` that defaults to true. This argument generates a `service.instance.id` value that is stable for the lifetime of the process.
[`AddService` requires passing a string for `service.name`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/core-1.12.0/src/OpenTelemetry/Resources/ResourceBuilderExtensions.cs#L37). Passing `builder.Environment.ApplicationName` sets the default `service.name` to the name of the assembly containing the service entrypoint. For this service it is the name is "cart" as cart.dll contains the entrypoint.
Screenshot of cart resource attributes after this change: …
> [cart] Generate `service.instance.id` resource attribute by default

- CHANGELOG.md
- src/grafana/provisioning/dashboards/demo/apm-dashboard.json
The APM Dashboards in Grafana point have a visualization table to show service logs from OpenSearch. This PR fixes the index-pattern pointing to OTel logs index in OpenSearch
> [grafana] Update OpenSearch logs index in APM Dashboards

- README.md
[Apache Doris](https://doris.apache.org/) is a modern OLAP database for real-time analytics. It delivers lightning-fast analytics on real-time data at scale. Doris is popular and its community is very active, with 13.4k github stars, 676 contributors and more than 5000 enterprise users.
One of its major user cases is logging and observability. It's already in the eco-system of [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/dorisexporter) as a storage backend. And the [doris-opentelemetry-demo](https://github.com/apache/doris-opentelemetry-demo) project is created to for Doris backend based on the latest offical opentelemetry-demo.
This PR try to add Apache Doris demo link in `README.md`. 
For new features contributions, please make …
> add Apache Doris in README.md

- .env
- CHANGELOG.md
This PR upgrades the Grafana version from 12.1.0 to 12.2.0.
Why? 
There is a bug in Grafana 12.1.0 related to the jaeger data source, where the data source doesn't respect subpaths in the jaeger url. This is causing jaeger to fail in this demo with the following error: `failed to decode Jaeger response: invalid character '<' looking for beginning of value`.
I fixed this bug a while back in grafana, and its available in 12.2.0 https://github.com/grafana/grafana/pull/109045.
Fixes #2589
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approver …
> Update grafana to 12.2.0
