open-telemetry/opentelemetry-demo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md, .github/workflows/stale.yml, .gitignore, .yamllint, Makefile, internal/tools/go.mod, internal/tools/go.sum, internal/tools/tools.go, package.json
Fixes #3.
* Updated the Discussions link. @open-telemetry/demo-webstore-maintainers need to decide if we want to use Discussions or something else (Issues, Slack, etc.).
* Fixed the CI.
* Minor fixes (wording, links).
=> Improve infra/ci

README.md
=> Fix contributor names

CODE_OF_CONDUCT.md, README.md, docs/cloudshell-tutorial.md, docs/cymbal-shops.md, docs/development-guide.md, docs/development-principles.md, docs/gcp-instrumentation.md, docs/memorystore.md, docs/service-mesh.md, docs/workload-identity.md
Cleaned up some of the markdown issues. Didn't remove all of them but covered most
=> fix some markdown issues

README.md
=> fix typo for readme

README.md
Removed some small sections & added structure for the local quickstart.
=> Small readme format updates

README.md
Just a small addition to the README.md that explains how people can quickly make the demo work with their own backend.
=> Add "Bring your own backend" section

README.md
ReadMe had an invalid link. 
https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/85
=> broken link fix 

README.md
=> fix typos for README.md

README.md, docs/v1Graph.md
Took me a second to get the hang of mermaid. Updated the readme to show the current architecture & color design of future architecture
=> Add colors to main readme mermaid

.github/.mlc_config.json, .github/workflows/checks.yml
=> github_action checks add job  markdown-link-check

README.md
Add honeycomb fork to readme list
=> Add Honeycomb fork

docker-compose.yml, src/cartservice/src/.dockerignore, src/cartservice/src/Dockerfile, src/cartservice/src/Startup.cs, src/cartservice/src/services/CartService.cs
Fixes #.
Fixes #140 
Re-added and referenced the CartService implementation
Added `ASPNETCORE_URLS` to the environment stanza of the cartservice definition in docker-compose
=> fix broken cartservice

src/checkoutservice/README.md
adding default feature table to checkout service readme
=> update feature table for checkout service

src/productcatalogservice/README.md
standard feature table for product catalog service
=> add feature set to product catalog

docker-compose.yml
The image url of featuregateservice is not same as others, I think it should be normalized.
=> normalize featuregateservice image url

src/checkoutservice/README.md, src/frontend/README.md, src/paymentservice/README.md, src/productcatalogservice/README.md
change emoji to improve readability. 
Add payment feature table
=> update emoji / add payment feature table

src/checkoutservice/README.md, src/frontend/README.md, src/paymentservice/README.md, src/productcatalogservice/README.md
=> quick fix to docs for extra emoji

src/emailservice/README.md
Updating feature table to match @julianocosta89's instrumentation updates
=> add ruby updated info for email service

.github/.mlc_config.json, README.md
Reword it a bit and add missing Prometheus endpoint
=> Update README section with the local endpoints

src/frontend/main.go
A small enhancement for frontend, the meter provider can be stop gracefully like trace provider
=> a small enhancement for frontend

CONTRIBUTING.md
Flesh out contributing markdown to provide a better onboarding experience
=> improve contributing md information

src/currencyservice/Dockerfile
Credit to this pr which is blocked by CLA: https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/205
Trying to get this closed & fixed.
Related issues:
https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/209
https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/208
=> update currency service docker file

docs/trace_service_features.md, src/checkoutservice/README.md, src/emailservice/README.md, src/frontend/README.md, src/paymentservice/README.md, src/productcatalogservice/README.md
updated per previous pr feedback
=> centralize a tracing doc

README.md
Added a couple badges to point to our slack and docker download. Open to adding more based on feedback or suggestions
=> add a couple badges to readme

docker-compose.yml
This upgrades the collector to v0.56.0
=> Update OTel collector to 0.56.0

docs/trace_service_features.md
Updates the Trace Feature coverage to a table, making it easier to read and consum
e
=> update trace feature coverage to a table

docs/metric_service_features.md
Updates the Metric Feature coverage to a table, making it easier to read and consume
=> update metric feature coverage to a table

docs/metric_service_features.md, docs/trace_service_features.md
Updating c++ and rust to be current. Added a non applicable option
=> Table update nits

docs/trace_service_features.md
nit update for erlang features
=> update erlang table entry

README.md
From Community SIG -- removing something confusing in README and clarify to use docker-compose
Remove Windows extra step
=> remove windows java guidance

src/currencyservice/Dockerfile
When updating the entry point section for the currency service the port wasn't being sent to the server code correctly, causing an error on the services dependent on this service.
=> 🐛 [CurrencyService] Fixing the currency service port

.github/workflows/release.yml
=> improve  release[github action]

.github/workflows/release.yml, Makefile
Fixes #323 
https://github.com/wph95/opentelemetry-demo-webstore/actions/runs/2892566725
Waiting for the test to pass. (Expected in 30-40 minutes)
The draft state will remain until the test passes.
=> fix release github action fail

docs/manual_span_attributes.md
- update description to be in line with other services
- small spelling fix
ref: https://docs.google.com/spreadsheets/d/1cGmYKfl9GAzCnQaG5iP-RoSZ-0R_Nm8hutg-EFotmsE/edit#gid=0
=> description updates on manual span attributes

docs/trace_service_features.md
@puckpuck as an FYI and to make sure I didn't miss an item. I put payment as under construction for baggage
=> update traces doc based on sig meeting

docker-compose.yml
hotfix due to broken docker on mac (& maybe other OS') https://github.com/open-telemetry/opentelemetry-demo/pull/304
@julianocosta89 it's building locally for me now but taking it's time
=> hotfix to comment out caching for now

docs/trace_service_features.md
=> nit update trace features product catalog

docker-compose.yml
fixes issue with fatal error being spammed in pg logs
=> add db and username to pg_isready

docs/services/recommendation.md
Adds documentation for recommendation service, focused on instrumentation code.
=> [recommendation] document instrumentation

.env
Updates IMAGE_VERSION to match the released version
=> update image version to v0.5.0-alpha

CHANGELOG.md
Small nit in changelog I missed
=> nit in changelog

README.md
=> Update vendor demo links

docs/services/checkoutservice.md
=> [checkoutservice] fix doc for checkoutservice

CONTRIBUTING.md
As a recent new contributor i thought below changes would improve the new contributor experience, so making below changes. Open to any feedback on this PR.
- Remove extra '-' in opentelemetry--demo which was a typo before
- Added some more steps to "How to Send Pull Requests" especially how to test changes locally
- Added links to FeatureFlag UI and Load Generator UI
- added "-d" flag so docker compose runs containers in background, this avoids needing to do "Ctrl +C" on Mac after the containers start. 
=> minor updates to CONTRIBUTING.md

docs/services/featureflagservice.md
Adds documentation for feature flag service, focused on instrumentation code.
=> [featureflag] document instrumentation

docs/README.md
Add an index page to the docs folder so we can more easily link to it.
=> Add docs index

docs/docker_deployment.md
- Add a new prerequisite for RAM
- Replace the backend configuration description with otelcol-config-extras.yml
=> Update docker deployment description

docfx.json
I don't think we're actively using this anymore
=> remove docfx

.github/workflows/release.yml
Fixes the env update and takes it out of the new matrix build (so it only happens once)
=> Fix Release Automation

.github/workflows/release.yml, CHANGELOG.md
Reverts open-telemetry/opentelemetry-demo#488
=> Revert "Images support multi arch"

.github/workflows/gradle-wrapper-validation.yml
For security (see https://github.com/gradle/wrapper-validation-action#the-gradle-wrapper-problem-in-open-source)
=> Add gradle wrapper validation

docs/services/frontend.md
Fixes review comment from #515
=> Front End -> Frontend

src/grafana/provisioning/dashboards/general/opentelemetry-collector.json
=> fix dashboard bugs

docker-compose.yml, src/paymentservice/index.js, src/paymentservice/package-lock.json, src/paymentservice/package.json, src/quoteservice/Dockerfile
In support of #458, this PR is making an attempt to improve build times by optimizing gRPC libs where possible/easy.
=> Improve build times for JS and PHP

src/otelcollector/otelcol-config.yml
=> Formatting: otelcol-config.yml

docker-compose.yml
Addresses regression from https://github.com/open-telemetry/opentelemetry-demo/pull/546
=> Fix PHP Traces

src/paymentservice/charge.js, src/paymentservice/index.js, src/paymentservice/logger.js, src/paymentservice/package-lock.json, src/paymentservice/tracing.js
Use Pino's [mergingObject](https://github.com/pinojs/pino/blob/master/docs/api.md#mergingobject-object) parameter to add context as JSON
rather than in the message parameter, which is now more generic (like an event name).
Also factor out logger so it is instantiated once for the whole service and upgrade pino.
Also remove unneeded comments.
=> paymentsservice: structure logs

README.md
fix https://github.com/open-telemetry/opentelemetry-demo/issues/579
=> add juliano as a maintainer

README.md
Small fixes based on feedback from @reyang
=> update emeritus formatting

README.md
Added Appdynamics to vendor list.
=> added appdynamics  to vendor

README.md
PR adds Sumo Logic on the list of demos.
=> feat(readme): add sumo logic

.env
=> Prep for 1.2

.github/workflows/release.yml
The new images didn't get added to the release workflow properly
=> Update release workflow to add new images

README.md
=> Add  AlibabaCloud LogService  to vendor list

.dockerignore, src/frontend/components/CartDropdown/CartDropdown.styled.ts, src/frontend/components/CartDropdown/CartDropdown.tsx, src/frontend/pages/_document.tsx
Towards #327 
Also fixed typo.
=> [frontend] Fix minor bugs

README.md
Updated previous PR after merging Grafana: https://github.com/open-telemetry/opentelemetry-demo/pull/667
=> update vendors table

CHANGELOG.md
Adding some additional FE features to the changelog so theyll make the release notes
=> minor changelog additions

docs/current_architecture.md
=> Remove spurious \

CHANGELOG.md, src/quoteservice/Dockerfile, src/quoteservice/composer.json
Update slim auto-instrumentation to beta4, and remove psr-15 auto-instrumentation.
Fixes: #659
=> reduce quoteservice spans

docker-compose.yml
=> fixing container name nit - quote service

CHANGELOG.md, src/adservice/Dockerfile, src/frauddetectionservice/Dockerfile, src/kafka/Dockerfile
=> bump up otel java agent version to 1.23.0

.env
=> Prep for 1.3.1 release

src/featureflagservice/Dockerfile
=> Fix OTP version for arm64

CHANGELOG.md, src/featureflagservice/Dockerfile, src/grafana/provisioning/dashboards/general/spanmetrics-dashboard.json
Sample spanmetrics dashboard showing service and operational level throughputs and latencies.
=> spanmetrics dashboard premiere

CHANGELOG.md
Changelog entry for [PR #797](https://github.com/open-telemetry/opentelemetry-demo/pull/797)
=> Changelog entry for PR 797

README.md
=> Move Michael Maxwell to Emeritus

CHANGELOG.md, src/frontend/components/CartItems/CartItems.tsx
This fixes shipping calculation when the Comet Book product is added to the shopping cart. The logical expression was evaluated incorrectly.
Fixes one bug in https://github.com/open-telemetry/opentelemetry-demo/issues/327
=> Fix to shipping calculation

CHANGELOG.md
Who watches the watchmen?
Adding the changelog item I forgot
=> add kafka mem allocation to changelog

CHANGELOG.md, src/frontend/utils/telemetry/FrontendTracer.ts
Addresses https://github.com/open-telemetry/opentelemetry-demo/issues/802
=> Changed web tracer to use batch processor

CHANGELOG.md
=> update changelog for 1.4.0 release

docker-compose.minimal.yml
=> issue #1030 is addressed please check it.

.github/workflows/checks.yml
=> GHA: checks workflow: explicitly pass inputs to build-images

kubernetes/opentelemetry-demo.yaml
Updates Kubernetes manifest for 1.5 release running `make generate-kubernetes-manifests`
=> (chore): Kubernetes manifest for 1.5 release

src/otelcollector/otelcol-config.yml
Fixes an indent issue in the collector config introduced in [this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1134)
=> (otelccol) fix indent in configuration

README.md
Adding myself to the list of approvers on the project README after
being accepted as approver.
=> Add Cedric Ziel to list of approvers

docker-compose.minimal.yml, docker-compose.yml
Updates all dependent services and telemetry backend components to their latest stable release.
Also removes tests from docker-compose-minimal.yml
=> [chore] - update dependent services to latest stable

README.md
=> Juliano Costa - Update affiliation

CHANGELOG.md, src/loadgenerator/Dockerfile, src/recommendationservice/Dockerfile
This PR tries to fix build issue with 2 Python (loadgenerator and recommendationservice) services:
https://github.com/open-telemetry/opentelemetry-demo/actions/runs/7413697963
=> [loadgenerator and recommendationservice] Update python base image

CHANGELOG.md, docker-compose.yml
Updates Grafana to the latest.
=> [grafana] - update grafana to 10.2.3

kubernetes/opentelemetry-demo.yaml
ran `make generate-kubernetes-manifests`
Fixes #1336
=> [chore] - update kubernetes manifests

src/accountingservice/kafka/trace_interceptor.go, src/checkoutservice/main.go
- Use semantic convention v1.24.0 for accounting and checkout service
=> chore: use semantic convention v1.24.0

.env, test/tracetesting/checkout-service/place-order.yaml
Fix #1391
* ~[ ] `CHANGELOG.md` updated to document new feature additions~
* ~[ ] Appropriate documentation updates in the [docs][]~
* ~[ ] Appropriate Helm chart updates in the [helm-charts][]~
=> Update trace test sem conv

kubernetes/opentelemetry-demo.yaml
`make generate-kubernetes-manifests`
=> update to 1.8.0 release

CHANGELOG.md, src/cartservice/src/Program.cs, src/cartservice/src/cartservice.csproj
This PR adds Host Resource Detector to CartService.
=> [CartService] - Add Host Detector

src/checkoutservice/main.go
- Use `exception.message` key from semantic convention.
=> refactor(checkoutservice): use exception.message key from semantic convention

CHANGELOG.md, docker-compose.minimal.yml, docker-compose.yml
Added restart policy to compose files for frontend-proxy.
~~Appropriate documentation updates in the docs~~
~~Appropriate Helm chart updates in the helm-charts~~
=> [Frontend-proxy] Add restart policy to compose files

CHANGELOG.md, src/frontend/pages/product/[productId]/index.tsx
=> Reset quantity in frontend when product changes

.github/workflows/label-pr.yml
Updated the script to point to the correct octokit script call
=> [repo] Fix GHA label script

.github/workflows/label-pr.yml
Token needs to be able to write issues as well as read them
=> [fix] update permissions in label issue

CHANGELOG.md, docker-compose.yml
Export flagd traces to otel collector
=> [flagd] export flagd traces to otel collector

Makefile
Add link to feature flags docs to Makefile message
not applicable
=> Add link to feature flags docs

README.md
=> Update Datadog link in README

src/adservice/Dockerfile, src/frauddetectionservice/Dockerfile
Upgrade [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/) to 2.3.0
=> chore(deps): upgrade opentelemetry-java-instrumentation to 2.3.0

src/kafka/Dockerfile
=> chore(deps): upgrade opentelemetry-java-instrumentation for kafka to 2.3.0

kubernetes/opentelemetry-demo.yaml
Fixes: #1546
`make generate-kubernetes-manifests`
=> [chore] update Kubernetes manifest to 1.9.0

README.md
Reverts open-telemetry/opentelemetry-demo#1457
=> Revert "remove axoflow link"

CHANGELOG.md, src/loadgenerator/locustfile.py
Fixes: https://github.com/open-telemetry/opentelemetry-demo/issues/1564
=> fix(loadgenerator): use add_hooks openfeature method

.env, src/grafana/provisioning/datasources/opensearch.yaml
Bump Otel collector contrib and opensearch image version.
=> chore(deps): upgrade otel collector contrib and opensearch

CONTRIBUTING.md
Fix documentation SIG meeting schedule
=> docs: update sig meeting schedule

src/cartservice/README.md, src/cartservice/src/Dockerfile, src/cartservice/src/cartservice.csproj
This allows the solution to be opened in any .NET editor and compile straight away.
Removes the requirement to manually copy the proto files.
This also now copies the protobuf files into the docker container using the original folder name.
=> Resolve proto directory dynamically for dotnet cartservice

.env
Bump `.env` image version to `1.10` and update OTel Collector to latest.
=> Update demo image version

Makefile
Fixes: https://github.com/open-telemetry/opentelemetry-demo/issues/1603
=> fix: start-minimal make target

.github/workflows/component_build-images.yml, .github/workflows/force-build.yml
This PR should target native runners (amd64, arm64) for builds.
=> Use native runners

.github/workflows/force-build.yml
=> add secrets inheritance

.github/workflows/force-build.yml
Reverts open-telemetry/opentelemetry-demo#1614
=> Revert "add secrets inheritance"

.github/workflows/gradle-wrapper-validation.yml
[chore] replace gh action gradle/wrapper-validation-action by gradle/actions/wrapper-validation
ref https://github.com/gradle/wrapper-validation-action/releases/tag/v3.4.2
* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~
=> [chore] replace gh action gradle/wrapper-validation-action by gradle/actions/wrapper-validation

docker-compose.yml
=> fix: emailservice docker compose image

CHANGELOG.md, src/recommendationservice/recommendation_server.py
=> Update recommendation flag to match flagd configuration

src/checkoutservice/main.go
Moves away from the deprecated `DialContext` call and uses the recommended approach with `NewClient` instead.
~* [ ] Appropriate documentation updates in the [docs][]~
~* [ ] Appropriate Helm chart updates in the [helm-charts][]~
=> [checkout] update to NewClient call

.env, CHANGELOG.md
=> [release] 1.11.1

kubernetes/opentelemetry-demo.yaml
Changes from running: `make generate-kubernetes-manifests`
=> [chore] update k8s manifests to 1.11.1 release

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Cleans up some of the grammar in the issue and pull request templates using Grammarly.
=> [chrore] clean up grammar in templates

src/shippingservice/src/shipping_service.rs
Added `rpc.method` and `rpc.service` to shippingservice grpc spans
=> [shippingservice] set rpc.method and rpc.service

CONTRIBUTING.md, README.md
Upstream changed docs links, see failing CI: https://github.com/open-telemetry/opentelemetry-demo/actions/runs/10301979608/job/28514676839?pr=1700
=> docs: update contributing and membership links

CHANGELOG.md, ide-gen-proto.sh
=> Fix gen-proto for accountingservice

.env, docker-compose.minimal.yml, docker-compose.yml, src/grafana/provisioning/datasources/opensearch.yaml, test/tracetesting/Dockerfile
Bump dependencies and  fix #1691.
=> [chore] Bump dependencies

CHANGELOG.md, src/accountingservice/AccountingService.csproj
[accountservice, cartservice] Bump .NET packages
=> [accountingservice] Bump OTel .NET Auto to 1.8.0

.env, CHANGELOG.md, docker-compose.minimal.yml, docker-compose.yml, src/grafana/provisioning/datasources/opensearch.yaml
This PR moves the control of opensearch image version to .env file.
=> [chore] Move opensearch image version to .env file

.env, CHANGELOG.md, docker-compose.minimal.yml, docker-compose.yml, src/grafana/provisioning/datasources/opensearch.yaml
Revert #1743 due to discussion:
\https://github.com/open-telemetry/opentelemetry-demo/discussions/1756#discussioncomment-11098736
=> Revert #1743

.env, CHANGELOG.md
=> [release] 1.12.0

kubernetes/opentelemetry-demo.yaml
ran `make generate-kubernetes-manifests`
=> [chore] - update k8s manifests for 1.12.0 release

.env, docker-compose.yml, src/frontendproxy/envoy.tmpl.yaml
=> [Fix] flagd ui name

.env, src/grafana/provisioning/datasources/opensearch.yaml
This PR updates the versions of the dependents components to the latest release.
=> [chore] Bump components versions

kubernetes/opentelemetry-demo.yaml
This PR updates the k8s manifests based on Helm upgrade: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1422
This PR is just the result of `make generate-kubernetes-manifests`.
* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~
=> Update k8s manifest

src/accountingservice/Dockerfile
#1785 broke instrumentation for `Accounting Service`.
This PR brings the instrumentation back, with the multi-arch build change.
=> [accountingservice] fix-instrumentation

src/accountingservice/Dockerfile
Reverts open-telemetry/opentelemetry-demo#1805
The change made the traces from AccountingService disappear.
=> Revert "[accountingservice] fix-build-targetarch"

kubernetes/opentelemetry-demo.yaml
Update k8s deployment files after changes on Helm chart: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1442.
> This PR was created just with the changes from `make generate-kubernetes-manifests`
=> [chore] Update k8s manifests

kubernetes/opentelemetry-demo.yaml
PR created after running `make generate-kubernetes-manifests`.
=> [chore] Updated k8s manifests based on last Helm changes

.env
=> [chore] Demo 2.0.0 release prep

CHANGELOG.md, kubernetes/opentelemetry-demo.yaml
`make generate-kubernetes-manifests` and set CHANGELOG.md to 2.0.0 release.
Fixes: #1983
=> [chore] post 2.0.0 release

CHANGELOG.md, kubernetes/opentelemetry-demo.yaml
Update changelog.md and run `make generate-kubernetes-manifests`
=> [chore] post release 2.0.1

.env
This is the weekend, so if a maintainer is going to merge this please make sure to issue a release soon thereafter, or we can wait until Monday.
=> [chore] release 2.0.2 prep

Makefile
=> The build make target does not take into account $(DOCKER_COMPOSE_ENV)

CHANGELOG.md, src/product-catalog/main.go
=> [product-catalog] simplify span event name

CHANGELOG.md, src/grafana/provisioning/datasources/jaeger.yaml
Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/2159
[cast.webm](https://github.com/user-attachments/assets/71543b69-a722-43ef-b160-e2452ed651ef)
=> [grafana] configure `traceToLogs` integration

.github/dependabot.yml
Apologies @puckpuck and @rogercoll , looks like there was a spelling mistake in my last PR:
#2153
Please see the fix for the correction. 
=> fix: correct spelling in dependabot configuration

CHANGELOG.md, src/cart/src/Program.cs, src/cart/src/cart.csproj
This pull request updates the feature flag management implementation in the `cart` service by transitioning to a more modern and modular approach using OpenFeature's dependency injection and hosting capabilities. It also includes updates to the project dependencies to support these changes.
=> Refactor OpenFeature integration and add dependency injection support

src/cart/src/cart.csproj
Downgrading gRPC due to https://github.com/grpc/grpc/issues/38538
=> [chore] Downgrade gRPC

README.md
=> updated AppDynamics link

README.md
Add Parseable as a vendor to demos table with blog post link. 
=> Add Parseable to demos table with blog post link

src/cart/src/cartstore/ValkeyCartStore.cs
Logging IDs in `cart` has been broken for a while. This PR fixes the templating to log IDs properly.
BEFORE:
AFTER: 
=> Fix IDs  in cart logging

README.md
We forked the opentelemetry-demo repository to showcase how to make it work with [Tinybird](https://www.tinybird.co/observability) as a backend
=> docs: update README with Tinybird demo

.env, CHANGELOG.md
=> [chore] pre-release work
